PolymeshAssociation/polymesh-sdk

- package.json
- src/Polymesh.ts
- src/__tests__/Polymesh.ts
- src/polkadot/augment-api-query.ts
- src/polkadot/augment-api-tx.ts
- src/polkadot/augment-types.ts
- src/polkadot/polymesh/definitions.ts
- src/polkadot/polymesh/types.ts
- src/polkadot/types.ts
- src/utils/index.ts
- yarn.lock
Also fixed fetching security tokens with empty names and updated types to the latest mesh version
> fix: stop using apollo cache

- src/Polymesh.ts
- src/__tests__/Polymesh.ts
- src/api/entities/Identity/Authorizations.ts
- src/api/entities/Identity/__tests__/index.ts
- src/api/entities/SecurityToken/Compliance/Rules.ts
- src/api/entities/SecurityToken/Compliance/TrustedClaimIssuers.ts
- src/api/entities/SecurityToken/Compliance/__tests__/Rules.ts
- src/api/entities/SecurityToken/Compliance/__tests__/TrustedClaimIssuers.ts
- src/api/entities/SecurityToken/TokenHolders.ts
- src/api/entities/SecurityToken/Transfers.ts
- src/api/entities/SecurityToken/__tests__/TokenHolders.ts
- src/api/entities/SecurityToken/__tests__/Transfers.ts
- src/api/entities/SecurityToken/__tests__/index.ts
- src/api/entities/SecurityToken/index.ts
- src/api/entities/TickerReservation/index.ts
- src/api/procedures/__tests__/issueTokens.ts
- src/api/procedures/__tests__/modifyClaims.ts
- src/api/procedures/consumeAuthorizationRequests.ts
- src/api/procedures/issueTokens.ts
- src/api/procedures/modifyClaims.ts
- src/api/procedures/setTokenTrustedClaimIssuers.ts
- src/api/procedures/transferPolyX.ts
- src/base/Procedure.ts
- src/base/__tests__/PolymeshTransaction.ts
- src/base/__tests__/Procedure.ts
- src/testUtils/mocks/dataSources.ts
- src/utils/__tests__/index.ts
- src/utils/constants.ts
- src/utils/index.ts
Also added subscription to queries that didn't have it, fixed some import paths, improved comments
> feat: add support for historic queries

- src/api/entities/SecurityToken/Compliance/Rules.ts
- src/api/entities/SecurityToken/Compliance/__tests__/Rules.ts
- src/api/entities/SecurityToken/Transfers.ts
- src/polkadot/polymesh/definitions.ts
- src/polkadot/polymesh/types.ts
- src/testUtils/mocks/dataSources.ts
- src/types/index.ts
- src/utils/__tests__/index.ts
- src/utils/index.ts
Compliance namespace in the Security Token entity
> feat: add `rules.checkTransfer` and `rules.checkMint`

- src/api/entities/CurrentIdentity.ts
- src/api/entities/Instruction/__tests__/index.ts
- src/api/entities/TickerReservation/index.ts
- src/api/entities/Venue/__tests__/index.ts
- src/api/entities/Venue/index.ts
- src/api/entities/__tests__/CurrentAccount.ts
- src/api/entities/__tests__/CurrentIdentity.ts
- src/api/entities/types.ts
- src/api/procedures/__tests__/modifyInstructionAuthorization.ts
- src/api/procedures/index.ts
- src/api/procedures/modifyInstructionAuthorization.ts
- src/testUtils/mocks/dataSources.ts
- src/utils/__tests__/index.ts
- src/utils/index.ts
Also add `addInstruction` to `Venue`
> feat: add `getPendingInstructions` to `CurrentIdentity`

- src/Claims.ts
- src/types/index.ts
Addressing this convo: https://polymathnetwork.slack.com/archives/GL43F3BRN/p1611179577060000
- please advice if `CddClaim` is an appropriate name
https://polymath.atlassian.net/browse/MSDK-436
> adds cdd claim type

- src/api/entities/SecurityToken/Offerings.ts
- src/api/entities/SecurityToken/__tests__/Offerings.ts
- src/api/entities/Sto/__tests__/index.ts
- src/api/entities/Sto/types.ts
- src/api/procedures/modifyStoTimes.ts
- src/types/index.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
Also removed redundant properties from `StoDetails`
BREAKING CHANGE: rename `minimumInvestment` to `minInvestment` and remove `offeringAsset` from
`StoDetails`
> feat(offerings): add `offerings.get` to the Security Token entity

- scripts/transactions.json
- sonar-project.properties
- src/api/entities/SecurityToken/Checkpoints.ts
- src/api/entities/SecurityToken/__tests__/Checkpoints.ts
- src/api/entities/SecurityToken/index.ts
- src/api/procedures/__tests__/createCheckpoint.ts
- src/api/procedures/__tests__/modifyInstructionAffirmation.ts
- src/api/procedures/createCheckpoint.ts
- src/api/procedures/modifyInstructionAffirmation.ts
- src/internal.ts
- src/polkadot/augment-api-consts.ts
- src/polkadot/augment-api-errors.ts
- src/polkadot/augment-api-events.ts
- src/polkadot/augment-api-query.ts
- src/polkadot/augment-api-rpc.ts
- src/polkadot/augment-api-tx.ts
- src/polkadot/augment-types.ts
- src/polkadot/definitions.ts
- src/polkadot/polymesh/definitions.ts
- src/polkadot/polymesh/types.ts
- src/polkadot/schema.ts
- src/polkadot/types.ts
- src/testUtils/mocks/dataSources.ts
Also upgraded the SDK to use Polymesh 2.5
> feat(checkpoints): add `checkpoints.create` to the Security Token Entity

- src/Claims.ts
- src/Polymesh.ts
- src/api/entities/Checkpoint.ts
- src/api/entities/SecurityToken/Checkpoints.ts
- src/api/entities/SecurityToken/__tests__/Checkpoints.ts
- src/api/entities/__tests__/Checkpoint.ts
- src/internal.ts
- src/testUtils/mocks/entities.ts
- src/types/index.ts
Added `totalSupply` and `timestamp` to Checkpoint
> feat(checkpoints): add `Checkpoints.get` and create Checkpoint entity

- src/api/entities/DividendDistribution/__tests__/index.ts
- src/api/entities/DividendDistribution/index.ts
- src/api/entities/DividendDistribution/types.ts
- src/testUtils/mocks/entities.ts
- src/utils/constants.ts
Fetches all participants, their amounts and whether they have been paid
> feat(dividends): add `getParticipants`

- src/api/entities/SecurityToken/Compliance/Requirements.ts
- src/api/entities/SecurityToken/Settlements.ts
- src/api/entities/SecurityToken/TransferRestrictions/Count.ts
- src/api/entities/SecurityToken/TransferRestrictions/Percentage.ts
- src/api/entities/SecurityToken/TransferRestrictions/TransferRestrictionBase.ts
- src/api/entities/SecurityToken/TransferRestrictions/__tests__/TransferRestrictionBase.ts
- src/api/entities/SecurityToken/__tests__/Settlements.ts
- src/api/entities/SecurityToken/types.ts
- src/api/procedures/__tests__/addTransferRestriction.ts
- src/api/procedures/__tests__/setTransferRestrictions.ts
- src/api/procedures/addTransferRestriction.ts
- src/api/procedures/setTransferRestrictions.ts
- src/testUtils/mocks/dataSources.ts
- src/testUtils/mocks/entities.ts
- src/types/index.ts
- src/types/internal.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
This calls the `asset.canTransferGranular` RPC under the hood
> feat(settlements): implement `canTransfer`

- codegen.yml
- src/Middleware.ts
- src/api/entities/DefaultTrustedClaimIssuer.ts
- src/api/entities/NumberedPortfolio.ts
- src/api/entities/SecurityToken/index.ts
- src/base/PolymeshTransactionBatch.ts
- src/middleware/types.ts
- src/utils/__tests__/conversion.ts
- src/utils/__tests__/internal.ts
- src/utils/conversion.ts
- src/utils/internal.ts
Also refactored the conversions into a function
> fix(middleware): use proper type for dates coming from the middleware

- src/base/Context.ts
- src/base/__tests__/Context.ts
This reverts commit edad2aa10e70d85684e52fd6b3641ce5e025caf2, reversing
changes made to cd819c4fc63d114e2598f89d6fb4ebdfc80c376a.
> Revert "Merge pull request #524 from PolymathNetwork/fix/temp-fix-ss58format"

- src/api/procedures/__tests__/linkCaDocs.ts
- src/api/procedures/linkCaDocs.ts
https://polymath.atlassian.net/browse/MSDK-748
> fix: 🐛 MSDK-748 Handle CAId conversion in LinkCADocs

- src/api/procedures/createCheckpointSchedule.ts
Adds documents explaining the meaning of null values when creating a
CheckpointSchedule
> docs: ✏️ Add JSDoc comment to CreateCheckpointScheduleParams

- README.md
Added some basic badges for sonar, build, github issues
> chore: 🤖 Add badges to README.md

- src/base/Context.ts
- src/base/__tests__/Context.ts
- src/testUtils/mocks/dataSources.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
Returns a Polymesh error type to provide better context when the
createType fails for whatever reason
> feat: 🎸 Throw Polymesh error when createType errors

- src/Polymesh.ts
- src/base/Context.ts
- src/base/__tests__/Context.ts
https://polymath.atlassian.net/browse/DA-244
> fix: 🐛 Expose non-proxied polkadot client

- src/Network.ts
- src/__tests__/Network.ts
https://polymath.atlassian.net/browse/DA-247
> feat: 🎸 Expose SS58 format

- src/AccountManagement.ts
- src/__tests__/AccountManagement.ts
- src/api/procedures/__tests__/createMultiSig.ts
- src/api/procedures/createMultiSig.ts
- src/internal.ts
Adds createMultiSig procedure into AccountManagement
> feat: 🎸 Add createMultiSig procedure

- src/api/entities/Asset/index.ts
The current docs state that freeze and unfreeze affect minting, but this isn’t the case. Updated the docs to remove the minting part
DA-300
> docs: ✏️ Update freeze/unfreeze docs

- src/api/entities/DividendDistribution/__tests__/index.ts
- src/api/entities/DividendDistribution/index.ts
- src/api/entities/DividendDistribution/types.ts
- src/types/index.ts
Added two new attributes to `DistributionParticipant` interface
- `taxWithholdingPercentage`
- `amountAfterTax` (rounded upto 6 decimals) calculated as `amount - amount * tax`
DA-306
> feat: 🎸 Round post-tax dividend amounts

- src/Polymesh.ts
- src/__tests__/Polymesh.ts
- src/testUtils/mocks/dataSources.ts
- src/utils/__tests__/conversion.ts
- src/utils/__tests__/internal.ts
- src/utils/constants.ts
- src/utils/internal.ts
- Fetch and compare chain spec version as well as rpc node version with the expected ranges, throw if not compatible
- Throw an error instead of a warning when the chain versions aren't
within the expected ranges
https://polymath.atlassian.net/browse/DA-324
> feat: 🎸 validate chain spec version when connecting

- src/api/client/Assets.ts
- src/api/client/__tests__/Assets.ts
Adds method to get all assets on chain(supports pagination)
DA-367
> feat: 🎸 Add method to get all assets on chain (with pagination)

- src/api/client/Claims.ts
- src/api/client/Network.ts
- src/api/client/__tests__/Network.ts
- src/api/entities/Account.ts
- src/api/entities/Identity/AssetPermissions.ts
- src/api/entities/Instruction/__tests__/index.ts
- src/api/entities/Instruction/index.ts
- src/api/entities/__tests__/Account.ts
- src/middleware/__tests__/queriesV2.ts
- src/middleware/queriesV2.ts
- src/middleware/typesV2.ts
- src/types/internal.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
* Updated Middleware V2 enum values
* Updated GQL queries to support respective Enum fields
* Updated attribute types in all V2 functions to point to Middleware V2 Enums
DA-370
> chore: 🤖 Add support for Middleware V2 Enum values

- src/utils/internal.ts
Refactor src/utils/internal.ts to remove CALL console.log
None
N/A
N/A
> refactor: 💡 remove CALL console.log

- src/api/procedures/__tests__/removeAssetRequirement.ts
- src/api/procedures/removeAssetRequirement.ts
* Correct the condition to check if given requirement id exists in existing requirements for an Asset 
[DA-384](https://polymath.atlassian.net/browse/DA-384)
> fix: 🐛 Correct validation for removing asset requirements

- README.md
Update compatible version and docs url in readme.md
No
> docs: ✏️ update compatible version and docs url in readme.md

- README.md
- src/Polymesh.ts
Adds a warning to let people know to update their package.json file. We'll need to remove these changes when we pull into beta.
> fix: 🐛 add warning to use the new npm repository

- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
fixes inviteAccount by updating the Permissions type
N/A
[DA-398](https://polymath.atlassian.net/browse/DA-398)
> fix: 🐛 Fix inviteAccount method by updating the permission type

- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
> fix: 🐛 Fix transfer with memo

- src/base/PolymeshTransactionBase.ts
use GenericPolymeshTransaction<ReturnValue, TransformedReturnValue> in
onStatusChange handler defined in PolymeshTransactionBase. This makes it
easier to define functions to be passed to it
N/A
N/A
> feat: 🎸 use a more specific type for onStatusChange in txBase

- src/api/procedures/addInstruction.ts
- src/api/procedures/consumeAuthorizationRequests.ts
- src/api/procedures/modifyAssetTrustedClaimIssuers.ts
- src/api/procedures/modifyCaDefaultConfig.ts
- src/api/procedures/modifyClaims.ts
- src/types/internal.ts
- src/utils/internal.ts
This reduces the need to use the `tuple` util, hopefully making the code
a bit more idiomatic
> chore: 🤖 improve typing around `assembleBatchTransaction`

- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
use null byte padding instead of spaces when creating memos
N/A
[DA-403](https://polymesh.atlassian.net/browse/DA-403)
> feat: 🎸 revert to null padding for memos

- README.md
- sonar-project.properties
Sonar account reconfiguration
No
No
> chore: 🤖 Sonar account reconfiguration

- src/api/entities/Portfolio/__tests__/index.ts
- src/api/entities/Portfolio/index.ts
Remove zero check for locked assets in assetBalances
NA
DA-351
> chore: 🤖 Remove zero check for locked assets in assetBalances

- src/testUtils/mocks/dataSources.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
fixes issue where memo on portfolio movement would cause an error
None
N/A
> fix: 🐛 update MovePortfolioItem conversion to long type name

- src/api/entities/Asset/Checkpoints/index.ts
- src/api/entities/Asset/Compliance/Requirements.ts
- src/api/entities/Asset/CorporateActions/index.ts
- src/api/entities/Asset/index.ts
- src/api/entities/Checkpoint.ts
- src/api/entities/DividendDistribution/index.ts
- src/api/entities/Identity/AssetPermissions.ts
- src/api/entities/Identity/IdentityAuthorizations.ts
- src/api/entities/Identity/index.ts
- src/api/entities/Portfolio/index.ts
- src/api/entities/TickerReservation/index.ts
- src/api/procedures/addTransferRestriction.ts
- src/api/procedures/modifyInstructionAffirmation.ts
- src/api/procedures/payDividends.ts
- src/api/procedures/registerMetadata.ts
- src/api/procedures/removeAssetStat.ts
- src/base/Context.ts
- src/types/utils/index.ts
- src/utils/internal.ts
Added a type safe wrapper for `queryMulti`
NA
DA-133
> chore: 🤖 Type safe wrapper for queryMulti

- src/testUtils/mocks/dataSources.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
Merge master changes into beta branch
NA
NA
> Merge master into beta

- src/utils/__tests__/internal.ts
- src/utils/constants.ts
Update supported spec version to 5.1.2
NA
NA
> feat: 🎸 Update supported spec version to 5.1.2

- src/testUtils/mocks/dataSources.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
Merge `master` into `beta` branch
No
NA
> Merge `master` into `beta` branch

- src/api/client/AccountManagement.ts
- src/utils/__tests__/internal.ts
- src/utils/internal.ts
Allow string for account value while revoking permissions
NA
DA-47
> feat: 🎸 Support string type account for revoking permissions

- src/api/entities/Asset/Compliance/Requirements.ts
- src/api/entities/Asset/Compliance/__tests__/Requirements.ts
resolve issue where the types were not being created as Option for canSettle checks
✅ Closes: #889
None
[DA-462](https://polymesh.atlassian.net/browse/DA-462)
> fix: 🐛 asset.compliance.requirements.canSettle check

- src/utils/__tests__/internal.ts
- src/utils/constants.ts
Spec version updated to 5.1.20 and node version updated to 5.1.1
NA
DA-474
> feat: 🎸 Update supported spec & node versions

- src/api/entities/Venue/__tests__/index.ts
- src/api/entities/Venue/index.ts
- src/api/entities/Venue/types.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
Allows fetching historical instructions for a venue using middleware v2 (native Subquery)
NA
DA-167
> feat: 🎸 Support fetching historical instructions for a venue

- src/api/entities/Identity/__tests__/index.ts
- src/api/entities/Identity/index.ts
- src/middleware/__tests__/queriesV2.ts
- src/middleware/queriesV2.ts
- src/utils/conversion.ts
Fetch historical instructions using middleware v2 where a DID is involved
NA
DA-168
> feat: 🎸 Support fetching historical instructions for a DID

- src/api/entities/Instruction/__tests__/index.ts
- src/api/entities/Instruction/index.ts
Add `Instruction.onStatusChange`. This allows to subscribe on the status of an instruction
NA
DA-301
> feat: 🎸 Add `Instruction.onStatusChange`

- src/api/entities/Instruction/__tests__/index.ts
- src/api/entities/Instruction/index.ts
- src/api/procedures/__tests__/executeManualInstruction.ts
- src/api/procedures/__tests__/utils.ts
- src/api/procedures/executeManualInstruction.ts
- src/api/procedures/types.ts
- src/api/procedures/utils.ts
- src/internal.ts
Adds procedure to manually execute an instruction
NA
DA-503
> feat: 🎸 Add procedure to manually execute instruction

- src/utils/__tests__/internal.ts
- src/utils/constants.ts
- src/utils/internal.ts
Update compatible version to 5.2.x
NA
NA
> fix: 🐛 Update compatible version to 5.2.x

- src/utils/__tests__/internal.ts
- src/utils/constants.ts
- src/utils/internal.ts
Updates supported spec version and node version to 5.3.x 
NA
DA-571
> feat: 🎸 Add support for spec range 5.3.x

- src/api/entities/Instruction/index.ts
Correct instruction id description
> docs: ✏️ correct instruction id description

- README.md
- src/api/entities/Instruction/index.ts
- src/api/procedures/__tests__/utils.ts
- src/api/procedures/utils.ts
Allows to affirm or reject failed instructions
NA
NA
> fix: 🐛 Allows to affirm or reject failed instructions

- src/api/client/Network.ts
- src/api/client/__tests__/Network.ts
- src/middleware/__tests__/queriesV2.ts
- src/middleware/queriesV2.ts
- src/types/index.ts
Adds a new method to `Network` namespace, to fetch middleware metadata
NA
DA-760
> feat: 🎸 Add method to get middleware metadata

- babel.config.js
- src/api/client/Network.ts
- src/api/client/Polymesh.ts
- src/api/client/__tests__/Network.ts
- src/api/client/__tests__/Polymesh.ts
- src/base/Context.ts
- src/base/__tests__/Context.ts
- src/testUtils/mocks/dataSources.ts
Adds compatibility check for Middleware V2 URL with chain node URL. Throws if URL is invalid or points to another chain.
🧨 `Polymesh.connect` now throws if middleware V2 URL is not working or is incompatible with the node URL
DA-761
> feat: 🎸 Add middleware V2 compatibility check on initialization

- src/api/procedures/__tests__/consumeAddRelayerPayingKeyAuthorization.ts
There was a line in the PR - https://github.com/PolymeshAssociation/polymesh-sdk/pull/998 with missing tests (which was a bit confusing to figure out, but I got that covered in the lts PR). Added the missing case for 100% coverage
NA
NA
> test: 💍 Add tests for missing coverage lines

- scripts/prepareCodeForDocs.js
- src/api/entities/Instruction/__tests__/index.ts
- src/api/entities/Instruction/index.ts
- src/types/index.ts
- src/utils/__tests__/internal.ts
- src/utils/internal.ts
Add support for optional args procedures. This will help up pass optional parameters to those procedures which are converted from NoArgsProcedureMethod to ProcedureMethod
NA
NA
> chore: 🤖 Add support for optional arg procedures

- src/api/entities/Offering/index.ts
fundraiser is an option if 5.4 so should be unwrapped there as well
> fix: 🐛 unwrap fundraiser for 5.4 chains

- src/api/procedures/createAsset.ts
use `unwrapOrDefault` instead of `unwrap` in createAsset prepareStorage call
None
N/A
> fix: 🐛 create custom asset type for v6

- src/api/client/Polymesh.ts
Add polkadot doc comment to `Polymesh.connect`
None
[DA-838](https://polymesh.atlassian.net/browse/DA-838)
[DA-838]: https://polymesh.atlassian.net/browse/DA-838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add connect comment

- src/api/client/Network.ts
- src/api/client/__tests__/Network.ts
- src/api/entities/Account/__tests__/index.ts
- src/api/entities/Account/index.ts
- src/middleware/queries.ts
- src/types/index.ts
Add the block date and time to the method results
> feat: 🎸Add `blockDate` to `getTransactionByHash` and `getTransactionHistory`

- src/api/entities/Asset/NonFungible/Nft.ts
- src/api/entities/Asset/NonFungible/NftCollection.ts
- src/api/entities/Asset/NonFungible/index.ts
- src/api/entities/Asset/__tests__/NonFungible/Nft.ts
- src/api/entities/Asset/__tests__/NonFungible/NftCollection.ts
- src/api/entities/Asset/types.ts
- src/api/procedures/__tests__/issueNft.ts
- src/api/procedures/issueNft.ts
- src/api/procedures/types.ts
- src/internal.ts
- src/testUtils/mocks/dataSources.ts
- src/testUtils/mocks/entities.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
allow issuance of individual NFTs via `issue` defined on `NftCollection`
✅ Closes: [DA-877](https://polymesh.atlassian.net/browse/DA-877)
[DA-877]: https://polymesh.atlassian.net/browse/DA-877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 add `issue` to NftCollection to create NFTs

- src/api/client/Claims.ts
- src/api/client/__tests__/Claims.ts
- src/middleware/types.ts
- src/types/index.ts
adds a method to check if CustomClaimType exists using either id or name
returns { id, name } if found or null if not
https://polymesh.atlassian.net/browse/DA-894
> feat: 🎸 get CustomClaimType by id or name

- src/api/entities/Asset/NonFungible/Nft.ts
- src/api/entities/Asset/__tests__/NonFungible/Nft.ts
- src/api/procedures/__tests__/redeemNft.ts
- src/api/procedures/redeemNft.ts
- src/api/procedures/types.ts
- src/internal.ts
- src/testUtils/mocks/entities.ts
allow for redemption/burning of NFTs
None
[DA-900](https://polymesh.atlassian.net/browse/DA-900)
[DA-900]: https://polymesh.atlassian.net/browse/DA-900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 add NFT redeem

- src/api/entities/types.ts
So people can import `Nft` without using the "internal" folder
None
[DA-877](https://polymesh.atlassian.net/browse/DA-877)
[DA-877]: https://polymesh.atlassian.net/browse/DA-877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 export Nft as an importable type for consumers

- src/api/entities/MultiSigProposal/__tests__/index.ts
- src/api/entities/MultiSigProposal/index.ts
Adds `votes` method to `MultiSigProposal` entity
NA
DA-901
> feat: 🎸 Add method to get votes for a MultiSig proposal

- src/types/index.ts
fix docs warnings by exporting referenced middleware types
None
[DA-931](https://polymesh.atlassian.net/browse/DA-931)
[DA-931]: https://polymesh.atlassian.net/browse/DA-931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: ✏️ export public middleware types

- src/middleware/queries.ts
fixes error when getIssuedClaims is called and the result includes CustomClaim
https://polymesh.atlassian.net/browse/DA-895
> feat: 🎸 fix getIssued claims error on CustomClaim

- src/middleware/queries.ts
Correct the multisig proposal votes query
NA
DA-934
> fix: 🐛 Correct the multisig proposal votes query

- src/utils/__tests__/internal.ts
- src/utils/constants.ts
some queries may not work if a subquery instance is not v10
None
N/A
> feat: 🎸 warn if using SQ < 10.0.0

- .github/workflows/main.yml
- release.config.js
- src/api/entities/Account/__tests__/index.ts
- src/api/entities/Account/index.ts
Backport address formatting fix into v22
None
N/A
> Add 22 patch release

- .github/workflows/main.yml
- release.config.js
Attempt to get around this restriction: https://github.com/PolymeshAssociation/polymesh-sdk/issues/1103#issue-2032715327
> feat: 🎸 make 22-patch a prerelease

- scripts/transactions.json
- src/api/entities/Asset/NonFungible/Nft.ts
- src/api/entities/Asset/__tests__/NonFungible/Nft.ts
- src/generated/types.ts
- src/polkadot/augment-api-errors.ts
- src/polkadot/augment-api-events.ts
- src/polkadot/augment-api-query.ts
- src/polkadot/augment-api-tx.ts
- src/polkadot/lookup.ts
- src/polkadot/registry.ts
- src/polkadot/types-lookup.ts
* Updates the polkadot dependencies with chain 6.1.1
* Adds a new method `getOwner` to Nft to get the holder of the NFT
NA
DA-997
> feat: 🎸 Add method to get owner of a NFT

- src/api/entities/confidential/ConfidentialTransaction/index.ts
- src/api/entities/confidential/__tests__/ConfidentialTransaction/index.ts
- src/testUtils/mocks/dataSources.ts
- src/types/index.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
add method to get details for confidential transactions
None
✅ Closes: [DA-995](https://polymesh.atlassian.net/browse/DA-995)
[DA-995]: https://polymesh.atlassian.net/browse/DA-995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 add ConfidentialTransaction details method

- src/api/entities/confidential/ConfidentialTransaction/index.ts
- src/api/entities/confidential/__tests__/ConfidentialTransaction/index.ts
add method to fetch involved parties in a transaction
none
✅ Closes: [DA-991](https://polymesh.atlassian.net/browse/DA-991)
[DA-991]: https://polymesh.atlassian.net/browse/DA-991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 add `getInvolvedParties` to ConfidentialTransaction

- src/api/client/ConfidentialAccounts.ts
- src/api/client/ConfidentialAssets.ts
- src/api/client/Polymesh.ts
- src/api/client/__tests__/ConfidentialAccounts.ts
- src/api/client/__tests__/ConfidentialAssets.ts
- src/api/entities/confidential/ConfidentialAccount/index.ts
- src/api/entities/confidential/ConfidentialAsset/types.ts
- src/api/entities/confidential/__tests__/ConfidentialAccount/index.ts
- src/api/procedures/__tests__/createConfidentialAccount.ts
- src/api/procedures/__tests__/createConfidentialAsset.ts
- src/api/procedures/createConfidentialAccount.ts
- src/api/procedures/createConfidentialAsset.ts
- src/internal.ts
- src/testUtils/mocks/entities.ts
- src/utils/__tests__/conversion.ts
- src/utils/__tests__/internal.ts
- src/utils/conversion.ts
- src/utils/internal.ts
* Add method to create confidential asset
* Adds `ConfidentialAccount` namespace
* Adds methods to create confidential account
NA
DA-976, DA-978
> feat: 🎸 Add methods for confidential account, asset creation

- src/api/client/ConfidentialSettlements.ts
- src/api/client/__tests__/ConfidentialSettlements.ts
- src/api/procedures/__tests__/createConfidentialVenue.ts
- src/api/procedures/createConfidentialVenue.ts
- src/internal.ts
Add a method to create a confidential venue
NA
DA-980
> feat: 🎸 Add method to create a confidential venue

- src/api/entities/confidential/ConfidentialTransaction/types.ts
- src/api/entities/confidential/ConfidentialVenue/index.ts
- src/api/entities/confidential/__tests__/ConfidentialVenue/index.ts
- src/api/entities/confidential/types.ts
- src/testUtils/mocks/entities.ts
This method returns all the transactions created by a confidential Venue. The result is grouped based on the status of the transaction
NA
DA-996
> feat: 🎸 Add `getTransactions` to Confidential Venue

- src/api/entities/confidential/ConfidentialAsset/index.ts
- src/api/entities/confidential/ConfidentialAsset/types.ts
- src/api/entities/confidential/__tests__/ConfidentialAsset/index.ts
- src/api/procedures/__tests__/setConfidentialVenueFiltering.ts
- src/api/procedures/setConfidentialVenueFiltering.ts
- src/internal.ts
Add venue filtering for confidential Assets
NA
DA-983
> feat: 🎸 Add venue filtering for confidential Assets

- src/api/entities/Identity/__tests__/index.ts
- src/api/entities/Identity/index.ts
- src/api/entities/Venue/index.ts
- src/api/entities/confidential/ConfidentialAccount/index.ts
- src/api/entities/confidential/ConfidentialVenue/index.ts
- src/api/entities/confidential/__tests__/ConfidentialAccount/index.ts
- src/api/entities/confidential/__tests__/ConfidentialVenue/index.ts
- src/api/procedures/__tests__/addConfidentialTransaction.ts
- src/api/procedures/addConfidentialTransaction.ts
- src/api/procedures/types.ts
- src/api/procedures/utils.ts
- src/internal.ts
- src/testUtils/mocks/dataSources.ts
- src/testUtils/mocks/entities.ts
- src/types/index.ts
- src/utils/__tests__/conversion.ts
- src/utils/__tests__/internal.ts
- src/utils/conversion.ts
- src/utils/internal.ts
- src/utils/typeguards.ts
allows venue owners to create confidential transactions with `addTransaction` and `addTransctions` methods
None
✅ Closes: [DA-981](https://polymesh.atlassian.net/browse/DA-981)
[DA-981]: https://polymesh.atlassian.net/browse/DA-981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 add `addTransaction` method to confidential venue

- src/api/entities/confidential/ConfidentialTransaction/index.ts
- src/api/entities/confidential/ConfidentialTransaction/types.ts
- src/api/entities/confidential/__tests__/ConfidentialTransaction/index.ts
- src/api/procedures/addConfidentialTransaction.ts
- src/api/procedures/types.ts
- src/api/procedures/utils.ts
- src/testUtils/mocks/dataSources.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
- src/utils/internal.ts
Add getLegs method for confidential transactions
None
✅ Closes: [DA-992](https://polymesh.atlassian.net/browse/DA-992)
[DA-992]: https://polymesh.atlassian.net/browse/DA-992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 add getLegs to confidential transaction

- src/api/entities/confidential/ConfidentialTransaction/index.ts
- src/api/entities/confidential/ConfidentialTransaction/types.ts
- src/api/entities/confidential/__tests__/ConfidentialTransaction/index.ts
- src/api/procedures/__tests__/executeConfidentialTransaction.ts
- src/api/procedures/executeConfidentialTransaction.ts
- src/internal.ts
- src/testUtils/mocks/entities.ts
- src/types/index.ts
- src/utils/conversion.ts
Adds a procedure to execute a confidential transaction
NA
DA-1036
> feat: 🎸 Add a procedure to execute a Confidential Transaction

- src/api/entities/Identity/__tests__/index.ts
- src/api/entities/Identity/index.ts
Adds a method to get all the confidential venues created by an Identity
NA
DA-1037
> feat: 🎸 Add `getConfidentialVenues` to Identity

- src/api/client/ConfidentialAssets.ts
- src/api/client/__tests__/ConfidentialAssets.ts
- src/api/procedures/createConfidentialAsset.ts
- src/utils/conversion.ts
Add method to get confidential asset from ticker
NA
DA-1039
> feat: 🎸 Add method to get Confidential Asset from ticker

- release.config.js
This will allow releasing of SDK with CA functionality. 
NA
NA
> feat: 🎸 Add release config for CA releases

- src/api/entities/Asset/Base/BaseAsset.ts
- src/api/entities/Asset/__tests__/Base/BaseAsset.ts
- src/api/entities/Asset/__tests__/Fungible/index.ts
- src/api/procedures/__tests__/addAssetMediators.ts
- src/api/procedures/__tests__/removeAssetMediators.ts
- src/api/procedures/addAssetMediators.ts
- src/api/procedures/removeAssetMediators.ts
- src/api/procedures/types.ts
- src/internal.ts
- src/testUtils/mocks/entities.ts
- src/utils/__tests__/conversion.ts
- src/utils/constants.ts
- src/utils/conversion.ts
add create, get, remove functions for asset required mediators
None
✅ Closes: [DA-1019](https://polymesh.atlassian.net/browse/DA-1019)
[DA-1019]: https://polymesh.atlassian.net/browse/DA-1019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 add asset required mediators functions

- src/api/client/ConfidentialAccounts.ts
- src/api/client/__tests__/ConfidentialAccounts.ts
- src/api/entities/confidential/ConfidentialAccount/index.ts
- src/api/entities/confidential/ConfidentialAccount/types.ts
- src/api/entities/confidential/__tests__/ConfidentialAccount/index.ts
- src/api/entities/confidential/types.ts
- src/api/procedures/__tests__/applyIncomingAssetBalance.ts
- src/api/procedures/applyIncomingAssetBalance.ts
- src/internal.ts
- src/testUtils/mocks/dataSources.ts
- src/testUtils/mocks/entities.ts
- tsconfig.json
Add methods for applying/getting incoming balance for CA
NA
DA-1076, DA-1077, DA-1040
> feat: 🎸 Add balance related methods for confidential account

- src/api/entities/Instruction/__tests__/index.ts
- src/api/entities/Instruction/index.ts
- src/api/entities/Instruction/types.ts
- src/testUtils/mocks/dataSources.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
add method to fetch instruction mediators, along with their affirmation status
None
✅ Closes: [DA-1024](https://polymesh.atlassian.net/browse/DA-1024)
[DA-1024]: https://polymesh.atlassian.net/browse/DA-1024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 add getMediators to Instruction

- src/api/entities/confidential/ConfidentialAsset/index.ts
- src/api/entities/confidential/__tests__/ConfidentialAsset/index.ts
- src/middleware/__tests__/queries.ts
- src/middleware/queries.ts
adds method to get createdAt for ConfidentialAsset
Requires SubQuery version with eventIdx added to ConfidentialAssets related entities
https://polymesh.atlassian.net/browse/DA-1033
> feat: 🎸 get creation date of ConfidentialAsset

- .vscode/settings.json
- scripts/transactions.json
- src/api/client/ConfidentialAccounts.ts
- src/api/client/ConfidentialAssets.ts
- src/api/client/__tests__/ConfidentialAccounts.ts
- src/api/client/__tests__/ConfidentialAssets.ts
- src/api/entities/confidential/ConfidentialAccount/index.ts
- src/api/entities/confidential/ConfidentialAccount/types.ts
- src/api/entities/confidential/ConfidentialAsset/index.ts
- src/api/entities/confidential/ConfidentialAsset/types.ts
- src/api/entities/confidential/ConfidentialTransaction/types.ts
- src/api/entities/confidential/__tests__/ConfidentialAccount/index.ts
- src/api/entities/confidential/__tests__/ConfidentialAsset/index.ts
- src/api/procedures/__tests__/applyIncomingAssetBalance.ts
- src/api/procedures/__tests__/createConfidentialAsset.ts
- src/api/procedures/__tests__/issueConfidentialAssets.ts
- src/api/procedures/applyIncomingAssetBalance.ts
- src/api/procedures/createConfidentialAsset.ts
- src/api/procedures/issueConfidentialAssets.ts
- src/generated/types.ts
- src/polkadot/augment-api-errors.ts
- src/polkadot/augment-api-events.ts
- src/polkadot/augment-api-query.ts
- src/polkadot/augment-api-tx.ts
- src/polkadot/lookup.ts
- src/polkadot/registry.ts
- src/polkadot/types-lookup.ts
Updates types after latest core changes. Fixes all the existing extrinsics and txtags to match the newly created ones.
Even though it has some breaking changes, I'm not marking them (since this is not yet live)
NA
- [] Updated the Readme.md (if required) ?
> feat: 🎸 Update polkadot-types and docs

- src/api/entities/confidential/ConfidentialAsset/index.ts
- src/api/entities/confidential/ConfidentialAsset/types.ts
- src/api/entities/confidential/__tests__/ConfidentialAsset/index.ts
- src/api/procedures/__tests__/burnConfidentialAssets.ts
- src/api/procedures/burnConfidentialAssets.ts
- src/internal.ts
- src/testUtils/mocks/dataSources.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
allow users to burn confidential assets
None
[DA-1084](https://polymesh.atlassian.net/browse/DA-1084)
[DA-1084]: https://polymesh.atlassian.net/browse/DA-1084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 add burn method for confidential assets

- src/api/entities/confidential/ConfidentialAsset/index.ts
- src/api/entities/confidential/__tests__/ConfidentialAsset/index.ts
- src/api/procedures/__tests__/toggleFreezeConfidentialAsset.ts
- src/api/procedures/toggleFreezeConfidentialAsset.ts
- src/internal.ts
- src/testUtils/mocks/entities.ts
add .freeze and .unfreeze methods to ConfidentialAsset and a isFrozen getter
None
✅ Closes: 
- [DA-1085](https://polymesh.atlassian.net/browse/DA-1086)
- [DA-1088](https://polymesh.atlassian.net/browse/DA-1088)
[DA-1085]: https://polymesh.atlassian.net/browse/DA-1085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DA-1088]: https://polymesh.atlassian.net/browse/DA-1088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 allow freeze/unfreeze of confidential assets

- scripts/transactions.json
- src/generated/types.ts
- src/polkadot/augment-api-errors.ts
- src/polkadot/augment-api-events.ts
- src/polkadot/augment-api-query.ts
- src/polkadot/augment-api-tx.ts
- src/polkadot/lookup.ts
- src/polkadot/registry.ts
- src/polkadot/types-lookup.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
adds support for a new error type for NFT canTransfer
[DA-1104](https://polymesh.atlassian.net/browse/DA-1104)
[DA-1104]: https://polymesh.atlassian.net/browse/DA-1104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: 🐛 handle NFT locked error in nft.canTransfer

- src/api/client/ConfidentialAccounts.ts
- src/api/client/__tests__/ConfidentialAccounts.ts
- src/api/entities/confidential/ConfidentialAccount/types.ts
- src/api/procedures/__tests__/applyIncomingConfidentialAssetBalances.ts
- src/api/procedures/applyIncomingConfidentialAssetBalances.ts
- src/internal.ts
- src/testUtils/mocks/entities.ts
- src/utils/__tests__/conversion.ts
- src/utils/constants.ts
- src/utils/conversion.ts
Adds a procedure to apply incoming balances for a CA
NA
DA-1087
> feat: 🎸 Add procedure to apply all incoming balances for CA

- LICENSE
- README.md
- SECURITY.md
> Remove references to Polymath

- package.json
- src/api/procedures/__tests__/modifyInstructionAffirmation.ts
- src/api/procedures/modifyInstructionAffirmation.ts
- src/polkadot/augment-api-errors.ts
- src/polkadot/augment-api-events.ts
- src/polkadot/lookup.ts
- src/polkadot/polymesh/definitions.ts
- src/polkadot/polymesh/types.ts
- src/polkadot/schema.ts
- src/polkadot/types-lookup.ts
- src/testUtils/mocks/dataSources.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
- yarn.lock
use "withCount" variations of affirmation extrinsics. this allows fees to be calculated more accurately
None
[DA-1082](https://polymesh.atlassian.net/browse/DA-1082)
[DA-1082]: https://polymesh.atlassian.net/browse/DA-1082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 reduce min balance needed to affirm

- src/api/entities/Asset/NonFungible/NftCollection.ts
- src/api/entities/Asset/__tests__/NonFungible/NftCollection.ts
- src/api/procedures/__tests__/nftControllerTransfer.ts
- src/api/procedures/nftControllerTransfer.ts
- src/api/procedures/types.ts
- src/internal.ts
- src/utils/conversion.ts
add method to allow controller transfers for NFTs
None
[DA-1004](https://polymesh.atlassian.net/browse/DA-1004)
[DA-1004]: https://polymesh.atlassian.net/browse/DA-1004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 add nftCollection.controller transfer

- src/api/client/Assets.ts
- src/api/entities/Asset/Base/BaseAsset.ts
- src/api/entities/Asset/Fungible/index.ts
- src/api/entities/Identity/AssetPermissions.ts
- src/api/entities/Identity/index.ts
- src/api/procedures/__tests__/modifyAsset.ts
- src/api/procedures/modifyAsset.ts
- src/testUtils/mocks/entities.ts
- src/utils/internal.ts
allow users to update NFT collection name, funding round and identitifiers. Adds getCurrentFundingRound method to retrive funding round for NFT collections
None
[DA-1004](https://polymesh.atlassian.net/browse/DA-1004)
[DA-1004]: https://polymesh.atlassian.net/browse/DA-1004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 add .modify to nft collection

- src/api/entities/Asset/NonFungible/NftCollection.ts
- src/api/entities/Asset/__tests__/NonFungible/NftCollection.ts
- src/api/entities/Asset/types.ts
- src/middleware/__tests__/queries.ts
- src/middleware/queries.ts
allow fetching transaction history of an NFT Collection
None
[DA-1004](https://polymesh.atlassian.net/browse/DA-1004)
[DA-1004]: https://polymesh.atlassian.net/browse/DA-1004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 add getTransactionHistory to NFT Collection

- src/api/procedures/createNftCollection.ts
- src/api/procedures/types.ts
add an optional `fundingRound` param to `CreateNftCollectionParams` interface
> feat: 🎸 allow funding round to be specified during nft create

- src/api/client/AccountManagement.ts
- src/api/client/Assets.ts
- src/api/client/Network.ts
- src/api/client/Polymesh.ts
- src/api/client/__tests__/Network.ts
- src/api/client/__tests__/Polymesh.ts
- src/api/entities/Account/index.ts
- src/api/entities/Asset/Base/BaseAsset.ts
- src/api/entities/Asset/Base/Compliance/Requirements.ts
- src/api/entities/Asset/Base/Compliance/TrustedClaimIssuers.ts
- src/api/entities/Asset/NonFungible/NftCollection.ts
- src/api/entities/Identity/index.ts
- src/api/entities/Instruction/index.ts
- src/api/entities/Offering/index.ts
- src/api/entities/Subsidies.ts
- src/api/entities/TickerReservation/index.ts
- src/base/Context.ts
- src/base/PolymeshTransactionBase.ts
- src/base/PolymeshTransactionBatch.ts
- src/base/__tests__/Context.ts
- src/base/__tests__/PolymeshTransactionBase.ts
- src/base/__tests__/utils.ts
- src/base/utils.ts
- src/testUtils/mocks/dataSources.ts
- src/utils/__tests__/conversion.ts
- src/utils/__tests__/internal.ts
- src/utils/conversion.ts
- src/utils/internal.ts
allow interacting with chain nodes by specifying an http based url when connecting to a node
None
✅ Closes: DA-531
> feat: 🎸 allow connection to nodes over http(s)

- src/api/entities/Asset/Base/Metadata/index.ts
- src/api/entities/Asset/__tests__/Base/Metadata.ts
- src/api/entities/MetadataEntry/types.ts
Add method to get all metadata associated with ticker having a value 
NA
DA-964
> feat: 🎸 Add method to get all fungible asset metadata details

- .github/workflows/fast-forward.yml
- .github/workflows/main.yml
Add support for fast-forward merges using https://github.com/marketplace/actions/fast-forward-merge
NA
DA-1161
> ci: 🎡 Add support for fast-forward merges

- scripts/fetchDefinitions.js
- src/api/client/Claims.ts
- src/api/client/Network.ts
- src/api/client/__tests__/Claims.ts
- src/api/client/__tests__/Network.ts
- src/api/entities/Account/__tests__/index.ts
- src/api/entities/Account/index.ts
- src/api/entities/Asset/Base/Settlements/index.ts
- src/api/entities/Asset/__tests__/Base/Settlements.ts
- src/api/entities/Identity/__tests__/index.ts
- src/api/entities/Identity/index.ts
- src/api/entities/common/namespaces/Authorizations.ts
- src/api/entities/common/namespaces/__tests__/Authorizations.ts
- src/api/procedures/__tests__/executeManualInstruction.ts
- src/api/procedures/__tests__/modifyInstructionAffirmation.ts
- src/api/procedures/executeManualInstruction.ts
- src/api/procedures/modifyInstructionAffirmation.ts
- src/base/PolymeshTransactionBase.ts
- src/base/__tests__/PolymeshTransactionBase.ts
- src/polkadot/schema.ts
- src/testUtils/mocks/dataSources.ts
- src/types/internal.ts
Use Runtime API calls to replace RPC wrapped calls
NA
DA-874
> feat: 🎸 Use Runtime API calls to replace RPC wrapped calls

- .github/workflows/fast-forward.yml
Right now the fast-forward doesn't trigger release. This add release action along with ff
> chore: 🤖 add release with fast-forwarding

- src/api/procedures/__tests__/createAsset.ts
- src/api/procedures/__tests__/createNftCollection.ts
- src/api/procedures/createAsset.ts
- src/api/procedures/createNftCollection.ts
- src/api/procedures/reserveTicker.ts
- src/utils/__tests__/internal.ts
- src/utils/internal.ts
allows usage of `_` `-` `.` and `/` in tickers
https://polymesh.atlassian.net/browse/DA-1153
> feat: 🎸 allow special characters for ticker

- .github/workflows/fast-forward.yml
- .github/workflows/main.yml
Remove the push event check on release step
NA
NA
> chore: 🤖 Remove the push event check on release step

- package.json
- src/api/procedures/__tests__/addInstruction.ts
- src/api/procedures/__tests__/utils.ts
- src/api/procedures/addInstruction.ts
- src/api/procedures/utils.ts
- yarn.lock
validate CDD claims when creating instructions
None
[DA-1166](https://polymesh.atlassian.net/browse/DA-1166)
[DA-1166]: https://polymesh.atlassian.net/browse/DA-1166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 ensure from and to have valid CDD for addInstruction

- src/api/client/AccountManagement.ts
- src/api/entities/Account/__tests__/index.ts
- src/api/entities/Identity/__tests__/index.ts
- src/api/entities/Identity/index.ts
- src/api/entities/types.ts
- src/utils/internal.ts
- adjusts `PermissionedAccount` so that 
account is either Account or MultiSig type
https://polymesh.atlassian.net/browse/DA-1163
> feat: 🎸 adjust permissioned account type for account

- src/base/Context.ts
allow for identity operations to be subsidized, as added in the chain 6.3 release
None
None
> feat: 🎸 update supportsSubsidy list to allow identity pallet

- src/base/Context.ts
allow balances pallet to be subsidized
None
None
> feat: 🎸 allow balances pallet to be subsidized

- .github/workflows/fast-forward.yml
This adds support for fast forwarding with PR comments
NA
DA-1215
> chore: 🤖 add support for fast-forward github action

- .github/workflows/authenticate-commits.yml
Add action to authenticate commits
NA
DA-1216
> ci: 🎡 Add action to authenticate commits

- src/api/entities/Venue/__tests__/index.ts
- src/api/entities/Venue/index.ts
- src/api/procedures/__tests__/createVenue.ts
- src/api/procedures/__tests__/updateVenueSigners.ts
- src/api/procedures/createVenue.ts
- src/api/procedures/types.ts
- src/api/procedures/updateVenueSigners.ts
- src/internal.ts
Adds option to add remove venue signers. 
Also, adds optional `signers` param to `CreateVenueParams` allowing to add signers while creating the Venue.
NA
DA-1229
> feat: 🎸 Add option to add/remove venue signers

- src/api/entities/Account/__tests__/index.ts
- src/api/entities/Account/index.ts
- src/api/entities/Identity/__tests__/Portfolios.ts
- src/api/entities/Instruction/__tests__/index.ts
- src/api/entities/Instruction/index.ts
- src/api/entities/Instruction/types.ts
- src/api/entities/Portfolio/__tests__/index.ts
- src/api/entities/Venue/__tests__/index.ts
- src/api/entities/Venue/index.ts
- src/api/procedures/__tests__/addInstruction.ts
- src/api/procedures/__tests__/createVenue.ts
- src/api/procedures/__tests__/executeManualInstruction.ts
- src/api/procedures/__tests__/modifyInstructionAffirmation.ts
- src/api/procedures/__tests__/updateVenueSigners.ts
- src/api/procedures/addInstruction.ts
- src/api/procedures/createVenue.ts
- src/api/procedures/executeManualInstruction.ts
- src/api/procedures/modifyInstructionAffirmation.ts
- src/api/procedures/types.ts
- src/api/procedures/updateVenueSigners.ts
- src/base/Context.ts
- src/base/__tests__/Context.ts
- src/internal.ts
- src/testUtils/mocks/dataSources.ts
- src/testUtils/mocks/entities.ts
- src/utils/__tests__/conversion.ts
- src/utils/constants.ts
- src/utils/conversion.ts
- src/utils/typeguards.ts
Adds support for off-chain settlements
DA-194
> feat: 🎸 Add support for off-chain settlements

- .github/workflows/authenticate-commits.yml
- src/middleware/queries.ts
remove querying for `updated_at` field from SubQuery
None
N/A
> feat: 🎸 remove updated_at in queries

- src/api/entities/Account/MultiSig/index.ts
- src/api/entities/Account/__tests__/MultiSig.ts
- src/base/Context.ts
- src/base/PolymeshError.ts
- src/middleware/queries.ts
fixed GraphQL error when fetching historical proposals. Also add `stack` attribute to PolymeshError
> fix: 🐛 `multiSig.getHistoricalProposal` errors

- src/base/PolymeshTransactionBase.ts
fixes `@hidden` being on a public property + add some more details to the comment
> docs: ✏️ remove @hidden from procedure .multiSig public property

- src/api/entities/types.ts
Export `MultiSigProposal` type
> feat: 🎸 export MultiSigProposal type

- src/base/PolymeshTransactionBase.ts
- src/base/__tests__/PolymeshTransactionBase.ts
- src/base/types.ts
add `multiSig` field that will be set when the offline payload is a MultiSig proposal
> feat: 🎸 add `multiSig` to `TransactionPayload`

- src/utils/typeguards.ts
add helper function to narrow `getAccount` return value to `MultiSig`
> feat: 🎸 add `isMultiSigAccount` typeguard

- src/api/procedures/__tests__/linkTickerToAsset.ts
- src/api/procedures/linkTickerToAsset.ts
batch a register ticker tx if needed when linking to an asset
[DA-1277](https://polymesh.atlassian.net/browse/DA-1277)
[DA-1277]: https://polymesh.atlassian.net/browse/DA-1277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 auto register ticker when linking to asset

- package.json
- src/api/entities/Instruction/__tests__/index.ts
- src/api/entities/Instruction/index.ts
- src/api/entities/Instruction/types.ts
- src/api/procedures/__tests__/addInstruction.ts
- src/api/procedures/addInstruction.ts
- src/api/procedures/executeManualInstruction.ts
- src/api/procedures/modifyInstructionAffirmation.ts
- src/testUtils/mocks/dataSources.ts
- yarn.lock
Handle optional venues for instruction processing
> feat: 🎸 handle optional venues when processing instruction

- src/api/client/Polymesh.ts
- src/api/entities/Account/__tests__/MultiSig.ts
- src/api/entities/Identity/__tests__/index.ts
- src/api/entities/Instruction/__tests__/index.ts
- src/api/entities/MultiSigProposal/__tests__/index.ts
- src/api/procedures/__tests__/createMultiSig.ts
- src/api/procedures/__tests__/createNftCollection.ts
- src/api/procedures/__tests__/evaluateMultiSigProposal.ts
- src/api/procedures/__tests__/executeManualInstruction.ts
- src/api/procedures/__tests__/modifyInstructionAffirmation.ts
- src/api/procedures/__tests__/modifyMultiSig.ts
- src/api/procedures/createNftCollection.ts
- src/api/procedures/modifyMultiSig.ts
- src/testUtils/mocks/dataSources.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
Adds missing tests to make sonar coverage 100%
> test: 💍 Add missing tests

- .github/workflows/main.yml
- package.json
- src/api/entities/Account/MultiSig/index.ts
- src/api/procedures/__tests__/evaluateMultiSigProposal.ts
- src/api/procedures/__tests__/modifyMultiSig.ts
- src/api/procedures/evaluateMultiSigProposal.ts
- src/api/procedures/modifyMultiSig.ts
- src/api/procedures/types.ts
- yarn.lock
MultiSig modify allows for requiredSignatures to be updated
MultiSig proposer can reject their proposal
Mark prior breaking change in instruction legs as breaking
[DA-1313](https://polymesh.atlassian.net/browse/DA-1313)
[DA-1313]: https://polymesh.atlassian.net/browse/DA-1313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release v25

- src/api/client/__tests__/Network.ts
- src/api/entities/Account/MultiSig/index.ts
- src/api/entities/Account/__tests__/MultiSig.ts
- src/api/procedures/__tests__/evaluateMultiSigProposal.ts
- src/api/procedures/__tests__/setMultiSigAdmin.ts
- src/api/procedures/evaluateMultiSigProposal.ts
- src/api/procedures/setMultiSigAdmin.ts
- src/api/procedures/types.ts
- src/internal.ts
- src/testUtils/mocks/dataSources.ts
allow for management of a multiSig admin for v7 chains. Signers can create a proposal to set an admin and an admin can relinquish the privilege
> feat: 🎸 add set admin method to multi instance

- src/api/entities/Account/MultiSig/index.ts
- src/api/entities/Account/__tests__/MultiSig.ts
- src/api/procedures/__tests__/removeMultiSigPayer.ts
- src/api/procedures/__tests__/setMultiSigAdmin.ts
- src/api/procedures/removeMultiSigPayer.ts
- src/internal.ts
Add `removePayer` to MultiSig
✅ Closes: DA-1317
> feat: 🎸 allow removal of a multiSig payer

- src/api/procedures/__tests__/consumeJoinOrRotateAuthorization.ts
- src/api/procedures/__tests__/utils.ts
- src/api/procedures/types.ts
- src/api/procedures/utils.ts
Release rotate secondary bug fix + export type for docs
> Alpha into beta

- package.json
- src/api/client/Polymesh.ts
- src/api/procedures/__tests__/redeemNft.ts
- src/api/procedures/redeemNft.ts
- src/polkadot/augment-api-consts.ts
- src/polkadot/augment-api-errors.ts
- src/polkadot/augment-api-events.ts
- src/polkadot/augment-api-query.ts
- src/polkadot/augment-api-tx.ts
- src/polkadot/lookup.ts
- src/polkadot/polymesh/definitions.ts
- src/polkadot/polymesh/types.ts
- src/polkadot/registry.ts
- src/polkadot/schema.ts
- src/polkadot/types-lookup.ts
- src/testUtils/mocks/dataSources.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
- yarn.lock
Update v7 types + passs in count for NFT redeem
None
[DA-1318](https://polymesh.atlassian.net/browse/DA-1318)
[DA-1318]: https://polymesh.atlassian.net/browse/DA-1318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update dual types

- package.json
- src/polkadot/schema.ts
- yarn.lock
[DA-1281](https://polymesh.atlassian.net/browse/DA-1281)
[DA-1281]: https://polymesh.atlassian.net/browse/DA-1281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: 🐛 add stats transfer report runtime type

- README.md
- src/api/procedures/types.ts
Update readme + fix doc generator warning
> docs: ✏️ update readme + export join creator params

- src/api/entities/Account/__tests__/index.ts
- src/api/entities/Account/index.ts
- src/testUtils/mocks/dataSources.ts
Update the logic for generating next Asset ID for an account (to include genesis hash as well)
NA
DA-1332
> feat: 🎸 Use genesis hash to generate next Asset ID

- src/api/entities/Account/__tests__/index.ts
- src/api/entities/Account/index.ts
- src/api/entities/Asset/Base/BaseAsset.ts
- src/api/entities/Asset/__tests__/Base/BaseAsset.ts
- src/api/procedures/__tests__/unlinkTickerFromAsset.ts
- src/api/procedures/unlinkTickerFromAsset.ts
- src/internal.ts
- src/testUtils/mocks/dataSources.ts
Add procedure to unlink ticker from an Asset
NA
DA-1334
> feat: 🎸 Add procedure to unlink ticker from an Asset

- src/api/procedures/__tests__/createAsset.ts
- src/api/procedures/createAsset.ts
- src/api/procedures/types.ts
Makes ticker optional while creating an asset
NA
DA-1338
> feat: 🎸 Make `ticker` optional while creating an asset

- src/api/client/__tests__/Claims.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
> fix: 🐛 Handle asset type middleware scope conversion correctly

- src/api/procedures/__tests__/addInstruction.ts
- src/api/procedures/__tests__/modifyInstructionAffirmation.ts
- src/api/procedures/addInstruction.ts
- src/api/procedures/modifyInstructionAffirmation.ts
- src/base/Context.ts
- src/base/__tests__/Context.ts
- src/polkadot/augment-api-consts.ts
- src/polkadot/augment-api-query.ts
- src/polkadot/augment-api-tx.ts
- src/polkadot/lookup.ts
- src/polkadot/types-lookup.ts
- src/testUtils/mocks/dataSources.ts
- src/utils/__tests__/conversion.ts
- src/utils/constants.ts
- src/utils/conversion.ts
Updates polkadot types using the latest BtreeSet changes on the core side (wrt instruction portfolios). Updates other logic to handle the BtreeSet values as well
NA
DA-1342
> feat: 🎸 Add support for btreeset portfolio ID

- src/api/entities/Asset/types.ts
- src/api/procedures/__tests__/addInstruction.ts
- src/api/procedures/__tests__/modifyInstructionAffirmation.ts
- src/api/procedures/addInstruction.ts
- src/api/procedures/modifyInstructionAffirmation.ts
- src/base/Context.ts
- src/base/__tests__/Context.ts
- src/polkadot/augment-api-consts.ts
- src/polkadot/augment-api-query.ts
- src/polkadot/augment-api-tx.ts
- src/polkadot/lookup.ts
- src/polkadot/types-lookup.ts
- src/testUtils/mocks/dataSources.ts
- src/utils/__tests__/conversion.ts
- src/utils/constants.ts
- src/utils/conversion.ts
> Support Btree portfolio sets

- src/middleware/__tests__/queries/claims.ts
- src/middleware/queries/claims.ts
fixes claims gql query by removing undefined values from variables
https://polymesh.atlassian.net/browse/DA-1356
> fix: 🐛 undefined variables corrupting claims gql

- src/api/procedures/__tests__/createNftCollection.ts
- src/api/procedures/createNftCollection.ts
Allows creation of nft collection with custom nft type string. Earlier error was thrown here
NA
DA-1335
> feat: 🎸 Allow creation of nft collection with custom nft type

- src/api/entities/Asset/Base/BaseAsset.ts
- src/api/entities/Asset/__tests__/Base/BaseAsset.ts
- src/api/procedures/__tests__/createAsset.ts
- src/api/procedures/createAsset.ts
add getter method to return asset ID in hex format
[DA-1345](https://polymesh.atlassian.net/browse/DA-1345)
[DA-1345]: https://polymesh.atlassian.net/browse/DA-1345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 add raw ID to BaseAsset class

- src/api/client/AccountManagement.ts
- src/api/client/Identities.ts
- src/api/client/Settlements.ts
- src/base/PolymeshTransaction.ts
- src/base/Procedure.ts
- src/utils/__tests__/strings.ts
- src/utils/strings.ts
add readonly to some class properties
> refactor: 💡 add readonly for sonar cloud

- src/api/client/Assets.ts
- src/api/client/__tests__/Assets.ts
- src/utils/__tests__/internal.ts
- src/utils/internal.ts
support hex input in a missed internal method
> feat: 🎸 support hex input in internal `asBaseAsset` method

- src/api/client/Claims.ts
- src/api/client/__tests__/Claims.ts
- src/api/entities/types.ts
- src/api/procedures/modifyClaims.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
- if middleware is enabled then claims.getClaimScopes will query middleware for CustomClaim scopes
- enables CustomClaim without a scope
https://polymesh.atlassian.net/browse/DA-1320
https://polymesh.atlassian.net/browse/DA-1358
> feat: 🎸 enable unscoped custom claims and fix get scopes

- Jenkinsfile
adds initial `Jenkinsfile`, for transitioning to jenkins artifact builds
NA
NO
> feat: 🎸 adds initial `Jenkinsfile`, for transitioning to jenkins artifact builds

- src/api/entities/Account/__tests__/index.ts
- src/api/entities/Account/index.ts
Handle multi sig signer key in account.getPermissions
NA
DA-1361
> fix: 🐛 Handle multiSig signer key in `account.getPermissions`

- src/api/client/Polymesh.ts
- src/api/client/__tests__/Claims.ts
- src/api/procedures/__tests__/addInstruction.ts
- src/api/procedures/__tests__/modifyInstructionAffirmation.ts
- src/api/procedures/addInstruction.ts
- src/api/procedures/modifyInstructionAffirmation.ts
- src/base/Context.ts
- src/base/__tests__/Context.ts
- src/utils/__tests__/internal.ts
- src/utils/constants.ts
- src/utils/internal.ts
update expected spec versions to account for upgraded polymesh private chains
> feat: 🎸 update supported polymesh private versions

- package.json
- yarn.lock
> Bump types

- src/base/PolymeshTransaction.ts
- src/base/PolymeshTransactionBase.ts
- src/base/PolymeshTransactionBatch.ts
- src/base/__tests__/PolymeshTransactionBase.ts
- src/base/__tests__/PolymeshTransactionBatch.ts
- src/utils/constants.ts
Add support for subsidized batches
NA
DA-1355
> feat: 🎸 Support subsidized batches

- Jenkinsfile
- package.json
- src/api/client/Claims.ts
- src/api/client/Polymesh.ts
- src/api/client/__tests__/Claims.ts
- src/api/entities/Account/__tests__/index.ts
- src/api/entities/Account/index.ts
- src/api/entities/types.ts
- src/api/procedures/__tests__/addInstruction.ts
- src/api/procedures/__tests__/modifyInstructionAffirmation.ts
- src/api/procedures/addInstruction.ts
- src/api/procedures/modifyClaims.ts
- src/api/procedures/modifyInstructionAffirmation.ts
- src/base/Context.ts
- src/base/PolymeshTransaction.ts
- src/base/PolymeshTransactionBase.ts
- src/base/PolymeshTransactionBatch.ts
- src/base/__tests__/Context.ts
- src/base/__tests__/PolymeshTransactionBase.ts
- src/base/__tests__/PolymeshTransactionBatch.ts
- src/utils/__tests__/conversion.ts
- src/utils/__tests__/internal.ts
- src/utils/constants.ts
- src/utils/conversion.ts
- src/utils/internal.ts
- yarn.lock
- support subsidized batches
- allow custom claims to be fetched from middleware
- handle multiSig signers in getPermissions
> support subsidized batches

- Jenkinsfile
- package.json
- src/api/client/Claims.ts
- src/api/client/Polymesh.ts
- src/api/client/__tests__/Claims.ts
- src/api/entities/Account/__tests__/index.ts
- src/api/entities/Account/index.ts
- src/api/entities/types.ts
- src/api/procedures/__tests__/addInstruction.ts
- src/api/procedures/__tests__/modifyInstructionAffirmation.ts
- src/api/procedures/addInstruction.ts
- src/api/procedures/modifyClaims.ts
- src/api/procedures/modifyInstructionAffirmation.ts
- src/base/Context.ts
- src/base/PolymeshTransaction.ts
- src/base/PolymeshTransactionBase.ts
- src/base/PolymeshTransactionBatch.ts
- src/base/__tests__/Context.ts
- src/base/__tests__/PolymeshTransactionBase.ts
- src/base/__tests__/PolymeshTransactionBatch.ts
- src/utils/__tests__/conversion.ts
- src/utils/__tests__/internal.ts
- src/utils/constants.ts
- src/utils/conversion.ts
- src/utils/internal.ts
- yarn.lock
Release new features and updates:
- custom claims can be queried for when GraphQL middleware is enabled
- multiSig signers are supported in getPermissions
- Batch transactions can be subsidized
> Release beta

- .eslintrc
- src/api/entities/Asset/Base/BaseAsset.ts
- src/api/procedures/__tests__/createAsset.ts
- src/api/procedures/__tests__/modifyAsset.ts
- src/api/procedures/createAsset.ts
- src/api/procedures/createNftCollection.ts
- src/api/procedures/modifyAsset.ts
- src/api/procedures/types.ts
- src/types/internal.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
- src/utils/internal.ts
- allows modification of assetType for FungibleAssets
https://polymesh.atlassian.net/browse/DA-1366
> feat: 🎸 allow modification of assetType

- src/api/entities/Instruction/index.ts
- src/api/entities/Venue/__tests__/index.ts
- src/api/entities/Venue/index.ts
- src/api/procedures/__tests__/executeManualInstruction.ts
- src/api/procedures/__tests__/modifyInstructionAffirmation.ts
- src/api/procedures/__tests__/utils.ts
- src/api/procedures/executeManualInstruction.ts
- src/api/procedures/modifyInstructionAffirmation.ts
- src/api/procedures/utils.ts
- src/testUtils/mocks/entities.ts
Fetch details from chain on instruction execution/affirmation
> fix: 🐛 Fetch details from chain on instruction execution/affirm

- src/api/procedures/__tests__/inviteAccount.ts
- src/api/procedures/inviteAccount.ts
- src/types/internal.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
- src/utils/internal.ts
fix handling new extrinsic format when transaction permissions are specified
[DA-1395](https://polymesh.atlassian.net/browse/DA-1395)
[DA-1395]: https://polymesh.atlassian.net/browse/DA-1395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: 🐛 getHistoricalAuthorization for v7 joinIdentity auth

- src/utils/internal.ts
> style: 💄 remove unused isV6 internal function

- src/api/procedures/__tests__/createNftCollection.ts
> test: 💍 add missing test case

- src/api/procedures/__tests__/createNftCollection.ts
> test: 💍 add nft creation with name test case

- src/utils/__tests__/internal.ts
- src/utils/constants.ts
provide warning for SubQuery less than v18.0.2
> refactor: 💡 bump min sq version to encourage upgrade

- release.config.js
> chore: 🤖 add v26 release config

- release.config.js
- src/api/entities/Instruction/index.ts
- src/utils/__tests__/internal.ts
- src/utils/constants.ts
Make Instruction `tradeDate` and `valueDate` Date type when fetching from middleware
> Fix instruction dates

- release.config.js
- src/api/entities/Instruction/index.ts
- src/utils/__tests__/internal.ts
- src/utils/constants.ts
Fix Instruction tradeDate and valueDate types when fetching from middleware
> Release Instruction trade and value date type

- release.config.js
> chore: 🤖 add channel to release config

- .github/workflows/main.yml
- release.config.js
- sonar-project.properties
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
> fix: 🐛 Use unique portfolios while creating BtreeSet

- src/api/entities/Instruction/index.ts
> fix: 🐛 handle `tradeDate` and `valueDate` of `null` in instruction details

- src/api/entities/Instruction/__tests__/index.ts
> test: 💍 add cases for null trade/value dates

- src/api/entities/Instruction/index.ts
- src/middleware/queries/settlements.ts
> fix: 🐛 fix instruction from middleware with SQ v19+

- src/middleware/queries/authorizations.ts
- src/middleware/queries/common.ts
- src/middleware/queries/settlements.ts
instruction and authorization IDs are no longer padded. Queries are updated accordingly
> feat: 🎸 update SQ v19 support for the latest changes

- src/api/entities/Instruction/__tests__/index.ts
- src/api/entities/Instruction/index.ts
> fix: 🐛 convert mediator affirmation expiry to `Date` and handle expiry of `null`

- src/api/entities/Account/__tests__/index.ts
- src/api/entities/Account/index.ts
- src/api/entities/Identity/__tests__/index.ts
- src/api/entities/Identity/index.ts
- src/api/entities/Instruction/__tests__/index.ts
- src/api/entities/Instruction/index.ts
- src/api/procedures/registerIdentity.ts
- src/middleware/__tests__/queries/assets.ts
- src/middleware/__tests__/queries/extrinsics.ts
- src/middleware/queries/assets.ts
- src/middleware/queries/authorizations.ts
- src/middleware/queries/common.ts
- src/middleware/queries/extrinsics.ts
- src/middleware/queries/settlements.ts
Fix SQ v19 ordering and registerIdentity serialization issue when targeting Account object (address string was fine)
> Release latest patches

- .vscode/settings.json
- src/api/entities/Account/Staking/index.ts
- src/api/entities/Account/__tests__/Staking.ts
- src/api/procedures/__tests__/unbondPolyx.ts
- src/api/procedures/bondPolyx.ts
- src/api/procedures/types.ts
- src/api/procedures/unbondPolyx.ts
- src/internal.ts
allow account to unbond POLYX with `Account.staking.unbond`
[DA-210](https://polymesh.atlassian.net/browse/DA-210)
[DA-210]: https://polymesh.atlassian.net/browse/DA-210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 add unbond to staking namespace

- src/utils/constants.ts
Add `7.1` to supported spec verison range
> feat: 🎸 Add `7.1` to supported spec verison range

- src/api/entities/Account/Staking/index.ts
- src/api/entities/Account/__tests__/Staking.ts
- src/api/entities/Account/types.ts
- src/api/procedures/__tests__/bondPolyx.ts
- src/api/procedures/__tests__/setStakingController.ts
- src/api/procedures/__tests__/setStakingPayee.ts
- src/api/procedures/bondPolyx.ts
- src/api/procedures/setStakingController.ts
- src/api/procedures/setStakingPayee.ts
- src/api/procedures/types.ts
- src/api/procedures/updateBondedPolyx.ts
- src/internal.ts
- src/testUtils/mocks/dataSources.ts
- src/testUtils/mocks/entities.ts
- src/utils/conversion.ts
- src/utils/internal.ts
allow a stash account to change its controller and a controller to change its reward destination
DA-209
> Set payee and controller

- src/api/entities/Account/Staking/index.ts
- src/api/entities/Account/__tests__/Staking.ts
- src/api/procedures/__tests__/updateBondedPolyx.ts
- src/api/procedures/__tests__/withdrawUnbondedPolyx.ts
- src/api/procedures/updateBondedPolyx.ts
- src/api/procedures/withdrawUnbondedPolyx.ts
- src/internal.ts
- src/testUtils/mocks/dataSources.ts
allow a controller to free unbonded POLYX for the stash account
[DA-211](https://polymesh.atlassian.net/browse/DA-211)
[DA-211]: https://polymesh.atlassian.net/browse/DA-211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 add staking.withdraw

- src/api/client/Staking.ts
- src/api/client/__tests__/Staking.ts
- src/api/entities/Account/Staking/index.ts
- src/api/entities/Account/__tests__/Staking.ts
- src/api/entities/Account/types.ts
- src/utils/conversion.ts
allow users to subscribe to an account's controller, nominations and eraInfo
[DA-1449](https://polymesh.atlassian.net/browse/DA-1449)
[DA-1449]: https://polymesh.atlassian.net/browse/DA-1449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 add subscription to staking getters

- src/api/client/Settlements.ts
- src/api/client/__tests__/Settlements.ts
- src/api/client/types.ts
- src/api/entities/Identity/__tests__/index.ts
- src/api/entities/Identity/index.ts
- src/middleware/__tests__/queries/settlements.ts
- src/middleware/queries/settlements.ts
- src/utils/constants.ts
Add 7.1 version check support (fixes warning) + bug fix for duplicate entries in historical instructions
> Add fix for historical instructions

- src/utils/__tests__/internal.ts
- src/utils/internal.ts
do no print warning on minor chain upgrade
> fix: 🐛 don't warn on minor chain upgrade

- src/api/client/Claims.ts
- src/api/client/__tests__/Claims.ts
- fixes infinite loop in calculating next records to fetch due to next being BigNumber(0) instead of null
https://polymesh.atlassian.net/browse/DA-1208
> fix: 🐛 getClaoimScope infinite loop

- src/api/entities/Asset/Fungible/CorporateActions/Ballots.ts
- src/api/entities/Asset/Fungible/CorporateActions/index.ts
- src/api/entities/CorporateBallot/__tests__/index.ts
- src/api/entities/CorporateBallot/index.ts
- src/internal.ts
- src/testUtils/mocks/dataSources.ts
- creates a namespace to hold corporate ballots-related functionality
-
https://polymesh.atlassian.net/browse/DA-1475
https://polymesh.atlassian.net/browse/DA-1478
> feat: 🎸 create ballots namespace

- src/api/entities/Asset/Fungible/CorporateActions/Ballots.ts
- src/api/entities/Asset/Fungible/CorporateActions/__tests__/Ballots.ts
- src/api/entities/CorporateBallot/__tests__/index.ts
- src/api/entities/CorporateBallot/index.ts
- src/testUtils/mocks/dataSources.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
- adds a method to retrieve a single ballot
https://polymesh.atlassian.net/browse/DA-1476
> feat: 🎸 get one existent ballot

- src/api/entities/Account/index.ts
- src/api/procedures/__tests__/addSecondaryAccountsWithAuth.ts
- src/api/procedures/__tests__/createChildIdentities.ts
- src/api/procedures/__tests__/createChildIdentity.ts
- src/api/procedures/__tests__/leaveIdentity.ts
- src/api/procedures/__tests__/modifySignerPermissions.ts
- src/api/procedures/__tests__/removeSecondaryAccounts.ts
- src/api/procedures/__tests__/rotatePrimaryKeyToSecondary.ts
- src/api/procedures/__tests__/unlinkChildIdentity.ts
- src/api/procedures/addSecondaryAccountsWithAuth.ts
- src/api/procedures/createChildIdentities.ts
- src/api/procedures/createChildIdentity.ts
- src/api/procedures/leaveIdentity.ts
- src/api/procedures/modifySignerPermissions.ts
- src/api/procedures/removeSecondaryAccounts.ts
- src/api/procedures/rotatePrimaryKeyToSecondary.ts
- src/api/procedures/unlinkChildIdentity.ts
- src/utils/__tests__/internal.ts
- src/utils/internal.ts
Compare accounts by addresses to solve the issue when one of the compared accounts is a multisig
NA
DA-1491
> fix: 🐛 compare accounts by addresses

- src/base/Context.ts
- src/utils/constants.ts
Add support for Staking and NFT pallets to be subsidized
NA
DA-1494
> feat: add support for Staking and NFT pallets to be subsidized

- src/api/procedures/__tests__/utils.ts
- src/api/procedures/utils.ts
Fix error when calculating compliance complexity
NA
DA-1498
> fix: 🐛 error when calculating compliance complexity

- src/api/procedures/__tests__/utils.ts
- src/api/procedures/utils.ts
Merge `alpha` into `beta`
NA
NA
> Merge `alpha` into `beta`

- src/api/procedures/__tests__/utils.ts
- src/api/procedures/utils.ts
> Release v27.4.1

- src/api/entities/Asset/Fungible/CorporateActions/Ballots.ts
- src/api/entities/Asset/Fungible/CorporateActions/__tests__/Ballots.ts
- src/testUtils/mocks/entities.ts
- adds method to retrieve all CorporateBallots for an Asset
https://polymesh.atlassian.net/browse/DA-1477
> feat: 🎸 get all CorporateBallots for an Asset

- scripts/transactions.json
- src/api/entities/Asset/Fungible/CorporateActions/Ballots.ts
- src/api/entities/Asset/Fungible/CorporateActions/__tests__/Ballots.ts
- src/api/entities/CorporateBallot/__tests__/index.ts
- src/api/entities/CorporateBallot/index.ts
- src/api/procedures/__tests__/createBallot.ts
- src/api/procedures/createBallot.ts
- src/api/procedures/types.ts
- src/generated/types.ts
- src/polkadot/augment-api-consts.ts
- src/polkadot/augment-api-errors.ts
- src/polkadot/augment-api-events.ts
- src/polkadot/augment-api-query.ts
- src/polkadot/augment-api-tx.ts
- src/polkadot/lookup.ts
- src/polkadot/registry.ts
- src/polkadot/types-lookup.ts
- src/testUtils/mocks/dataSources.ts
- src/testUtils/mocks/entities.ts
- src/utils/__tests__/conversion.ts
- src/utils/__tests__/internal.ts
- src/utils/constants.ts
- src/utils/conversion.ts
- src/utils/internal.ts
- updates polkadot types to support 7.2 chain
- adds method to create a CorporateBallot (initiate corporate action and ballot)
https://polymesh.atlassian.net/browse/DA-1483
> feat: 🎸 createBallot procedure

- src/api/entities/CorporateBallot/__tests__/index.ts
- src/api/entities/CorporateBallot/index.ts
- src/api/entities/CorporateBallot/types.ts
- get ballot status
https://polymesh.atlassian.net/browse/DA-1479
> feat: 🎸 get ballot status

- src/api/entities/CorporateBallot/__tests__/index.ts
- src/api/entities/CorporateBallot/index.ts
- src/api/entities/CorporateBallot/types.ts
get ballot results
https://polymesh.atlassian.net/browse/DA-1480
> feat: 🎸 get ballot results

- src/api/entities/CorporateBallot/__tests__/index.ts
- src/api/entities/CorporateBallot/index.ts
- src/api/entities/CorporateBallot/types.ts
get participation in a Ballot
https://polymesh.atlassian.net/browse/DA-1481
> feat: 🎸 did participation in CorporateBallot

- src/api/entities/CorporateBallot/__tests__/index.ts
- src/api/entities/CorporateBallot/index.ts
- src/api/procedures/__tests__/castBallotVote.ts
- src/api/procedures/castBallotVote.ts
- src/api/procedures/types.ts
- src/testUtils/mocks/entities.ts
- src/utils/__tests__/conversion.ts
- src/utils/conversion.ts
vote on corporate ballot
https://polymesh.atlassian.net/browse/DA-1482
> feat: 🎸 vote on CorporateBallot
