PolymeshAssociation/polymesh-sdk

src/api/entities/SecurityToken/Documents.ts, src/api/entities/SecurityToken/__tests__/Documents.ts
RPC method has some problem with document encoding.
We are reverting changes related to this issue until it is fixed.
=> fix: return to links entries version for documents (from #128)

src/Polymesh.ts, src/__tests__/Polymesh.ts, src/api/entities/Proposal/__tests__/index.ts, src/api/entities/Proposal/index.ts, src/api/procedures/__tests__/modifyClaims.ts, src/api/procedures/modifyClaims.ts, src/middleware/queries.ts, src/middleware/types.ts, src/types/index.ts, src/utils/__tests__/index.ts, src/utils/constants.ts, src/utils/index.ts
Paginated GQL queries return a ResultSet including the total amount of records for that query, the
next key if there are more pages and the data from the query.
BREAKING CHANGE: 
- getIssuedClaims and getIdentitiesWithClaims return ResultSet<IdentityWithClaims> instead of IdentityWithClaims[]
=> Feat/add count to GQL queries

src/Governance.ts, src/__tests__/Governance.ts, src/api/procedures/__tests__/createProposal.ts, src/api/procedures/createProposal.ts, src/context/__tests__/index.ts, src/context/index.ts, src/testUtils/mocks/dataSources.ts, src/types/index.ts, src/utils/constants.ts
This function receives a transaction tag and returns a list of the transaction's arguments and their
types
=> feat: add `Governance.getTransactionArguments`

src/__tests__/Polymesh.ts, src/api/procedures/__tests__/modifyClaims.ts, src/api/procedures/modifyClaims.ts, src/base/PolymeshError.ts, src/base/__tests__/PolymeshError.ts, src/base/types.ts, src/types/index.ts
These functions now receive an array of `ClaimTarget` (an object with a target DID, a claim and an
optional expiry)
BREAKING CHANGE: The `ClaimTargets` interface has been replaced with `ClaimTarget`. Instead of
representing a set of identities with one claim, it now represents a single identity/claim pair
=> feat: change inputs for `addClaims`, `editClaims` and `revokeClaims`

src/index.ts, src/types/index.ts
- export the `PolkadotSigner` type from `/types`
- export `BigNumber`, `Keyring` and `WsProvider` from the index
=> feat: export utility types and classes

src/Claims.ts, src/Polymesh.ts, src/api/entities/Account.ts, src/api/entities/CurrentAccount.ts, src/api/entities/Proposal/index.ts, src/api/entities/__tests__/Account.ts, src/api/entities/__tests__/CurrentAccount.ts, src/api/procedures/consumeAuthorizationRequests.ts, src/base/Context.ts, src/base/__tests__/Context.ts, src/index.ts, src/utils/index.ts
BREAKING CHANGE: `account.getIdentity()`, `currentAccount.getIdentity()` and `api.getCurrentIdentity()` now return null if the Identity doesn't exist (used to throw an error)
=> feat: return null when identity doesn't exist

src/api/entities/SecurityToken/index.ts, src/api/procedures/__tests__/issueTokens.ts, src/api/procedures/issueTokens.ts
If PIA is set to None, issuance should be possible, taking the token nowner as default PIA
=> fix: fix validation when PIA is set to None

src/api/entities/Identity/Portfolios.ts, src/api/entities/Identity/__tests__/Portfolios.ts, src/api/entities/Instruction/index.ts, src/api/entities/Instruction/types.ts, src/api/procedures/__tests__/addInstruction.ts, src/api/procedures/addInstruction.ts, src/testUtils/mocks/entities.ts, src/types/index.ts, src/utils/__tests__/index.ts, src/utils/index.ts
Also changed the `Leg` type
BREAKING CHANGE: `Leg.from` and `Leg.to` changed from `Identity` to `DefaultPortfolio |
NumberedPortfolio`. This affects the output of `Instruction.getLegs`
=> feat(instruction): accept portfolios as input when creating instructions

src/api/entities/AuthorizationRequest.ts, src/api/entities/__tests__/AuthorizationRequest.ts, src/api/procedures/__tests__/consumeJoinIdentityAuthorization.ts, src/api/procedures/consumeJoinIdentityAuthorization.ts, src/api/procedures/index.ts, src/base/PolymeshTransaction.ts, src/base/Procedure.ts, src/base/TransactionQueue.ts, src/base/__tests__/PolymeshTransaction.ts, src/base/__tests__/TransactionQueue.ts, src/polkadot/polymesh/definitions.ts, src/testUtils/mocks/polymeshTransaction.ts, src/types/internal.ts
Adjusted how we handle third party fees
BREAKING CHANGE: `PolymeshTransaction.getFees` no longer returns fees as 0 when they are paid by a
third party. This is now reflected by a `paidByThirdParty` flag
=> fix: reject `JoinIdentity` authorizations correctly

package.json, src/api/entities/SecurityToken/Compliance/Requirements.ts, src/api/entities/SecurityToken/Compliance/__tests__/Requirements.ts, src/base/Context.ts, src/polkadot/augment-api-query.ts, src/polkadot/augment-api-tx.ts, src/polkadot/augment-types.ts, src/polkadot/polymesh/definitions.ts, src/polkadot/polymesh/types.ts, src/testUtils/mocks/dataSources.ts, src/types/index.ts, src/utils/__tests__/index.ts, src/utils/index.ts, yarn.lock
Also updated checkSettle compliance result types
BREAKING CHANGE: `RequirementCompliance` renamed to `Compliance`. There is now a new type called
`RequirementCompliance` which represents compliance to a specific asset requirement. Each condition
inside it has its own `complies` flag
=> chore(polkadot): upgrade types and polkadot API version

src/Polymesh.ts, src/__tests__/Polymesh.ts, src/api/entities/SecurityToken/index.ts, src/utils/__tests__/conversion.ts, src/utils/__tests__/internal.ts, src/utils/conversion.ts, src/utils/internal.ts
Also validate that tickers do not contain unreadable characters when creating a reservation
=> fix: filter out unreadable tickers when fetching reservations and tokens

src/api/entities/DefaultTrustedClaimIssuer.ts, src/api/entities/SecurityToken/Compliance/TrustedClaimIssuers.ts, src/api/entities/SecurityToken/Compliance/__tests__/TrustedClaimIssuers.ts, src/api/entities/__tests__/DefaultTrustedClaimIssuer.ts, src/api/procedures/__tests__/modifyTokenTrustedClaimIssuers.ts, src/api/procedures/modifyTokenTrustedClaimIssuers.ts, src/internal.ts, src/types/index.ts, src/utils/__tests__/conversion.ts, src/utils/conversion.ts
Methods that modify default trusted claim issuers for a token now require passing Claim Types for
which that issuer is trusted
BREAKING CHANGE: - `TrustedClaimIssuers.set` and `TrustedClaimIssuers.add` now require an array of
`TrustedClaimIssuer` objects (each with an identity and an array of ClaimTypes)
=> feat(trusted claim issuers): require trusted claim types on claimissuers

src/api/entities/CurrentAccount.ts, src/api/entities/__tests__/CurrentAccount.ts
Retrieves the Permissions the Current Account has as a Signing Key for its corresponding Identity
=> feat(current account): add `getPermissions`

src/api/entities/SecurityToken/Compliance/TrustedClaimIssuers.ts, src/api/procedures/__tests__/modifyTokenTrustedClaimIssuers.ts, src/api/procedures/modifyTokenTrustedClaimIssuers.ts
Methods that modify Default Trusted Claim Issuers now also accept DIDs to represent the Claim
Issuer. Also fixed a bug in `TrustedClaimIssuers.get`
=> feat(trusted claim issuers): support DID strings as well as Identity

src/api/entities/Portfolio/types.ts, src/api/entities/SecurityToken/TokenHolders.ts, src/api/entities/Sto/__tests__/index.ts, src/api/entities/Sto/index.ts, src/api/procedures/__tests__/closeSto.ts, src/api/procedures/__tests__/modifyStoTimes.ts, src/api/procedures/addInstruction.ts, src/api/procedures/closeSto.ts, src/api/procedures/modifyStoTimes.ts, src/internal.ts
Also remove redundant parameter from `close` method
BREAKING CHANGE: `sto.close` now takes no parameters
=> feat: add `modifyTimes` to the STO entity

src/api/entities/CurrentAccount.ts, src/api/entities/__tests__/CurrentAccount.ts, src/api/procedures/modifySignerPermissions.ts, src/utils/__tests__/conversion.ts, src/utils/conversion.ts
Also exempted some transactions from requiring permissions (most of balances, all of staking, sudo
and session)
=> fix(permissions): order permissions alphabetically before setting them

src/api/entities/Identity/__tests__/index.ts, src/api/entities/Identity/index.ts, src/api/entities/SecurityToken/TransferRestrictions/Count.ts, src/api/entities/SecurityToken/TransferRestrictions/Percentage.ts, src/api/entities/SecurityToken/TransferRestrictions/TransferRestrictionBase.ts, src/api/entities/SecurityToken/TransferRestrictions/__tests__/TransferRestrictionBase.ts, src/api/procedures/__tests__/addTransferRestriction.ts, src/api/procedures/__tests__/setTransferRestrictions.ts, src/api/procedures/addTransferRestriction.ts, src/api/procedures/setTransferRestrictions.ts, src/testUtils/mocks/entities.ts, src/types/index.ts
Also added an `Identity.getScopeId` getter
BREAKING CHANGE:
- rename `exempted` to `exemptedScopeIds` in `CountTransferRestriction` and `PercentageTransferRestriction`
- rename `exempted` to `exemptedScopeIds` and add `exemptedIdentities` to the parameters of `addRestriction` and `setRestrictions` in both restriction namespaces
=> feat(restrictions): allow identities as exempted

src/api/entities/SecurityToken/Offerings.ts, src/api/entities/SecurityToken/__tests__/Offerings.ts, src/api/entities/Sto/__tests__/index.ts, src/api/entities/Sto/types.ts, src/api/procedures/__tests__/closeSto.ts, src/api/procedures/__tests__/investInSto.ts, src/api/procedures/__tests__/modifyStoTimes.ts, src/api/procedures/__tests__/toggleFreezeSto.ts, src/api/procedures/closeSto.ts, src/api/procedures/investInSto.ts, src/api/procedures/modifyStoTimes.ts, src/api/procedures/toggleFreezeSto.ts, src/testUtils/mocks/dataSources.ts, src/testUtils/mocks/entities.ts, src/types/index.ts, src/utils/__tests__/conversion.ts, src/utils/conversion.ts
Added total offering amount, total remaining tokens and refined status
BREAKING CHANGE: Sto status is now divided into `timing`, `sale` and `balance`
=> feat(sto): improve offering details

src/Polymesh.ts, src/api/entities/Checkpoint.ts, src/api/entities/SecurityToken/TokenHolders.ts, src/api/entities/__tests__/Checkpoint.ts
`allBalances` fetches all balances and can be paginated, `balance` fetches it for a single identity
=> feat(sto): add balance fetching methods to Checkpoint entity

src/api/entities/Instruction/__tests__/index.ts, src/api/entities/Instruction/index.ts, src/api/entities/Venue/__tests__/index.ts, src/api/entities/Venue/index.ts, src/api/entities/__tests__/CurrentIdentity.ts, src/testUtils/mocks/dataSources.ts, src/testUtils/mocks/entities.ts
Added `Instruction.exists` and throw a more explicit error when fetching a pruned instruction's
details
=> fix(instructions): properly ignore pruned venue instructions

src/api/entities/SecurityToken/CorporateActions/__tests__/index.ts, src/api/entities/SecurityToken/CorporateActions/index.ts, src/api/entities/SecurityToken/CorporateActions/types.ts, src/api/entities/SecurityToken/types.ts, src/utils/__tests__/conversion.ts, src/utils/conversion.ts
Returns the default CA targets, base tax withholding percentage and per-identity tax withholding
percentages for the ST
=> feat(corporate actions): add `getDefaults`

src/api/entities/CorporateAction/types.ts, src/api/entities/SecurityToken/CorporateActions/__tests__/index.ts, src/api/entities/SecurityToken/CorporateActions/index.ts, src/api/procedures/__tests__/initiateCorporateAction.ts, src/api/procedures/__tests__/modifyCaDefaults.ts, src/api/procedures/__tests__/utils.ts, src/api/procedures/initiateCorporateAction.ts, src/api/procedures/modifyCaDefaults.ts, src/api/procedures/utils.ts, src/internal.ts, src/testUtils/mocks/entities.ts
Allows to set default targets, global tax withholding % and per-identity tax withholding %
=> feat(corporate actions): add `setDefaults` to the namespace

src/Polymesh.ts, src/__tests__/Polymesh.ts, src/api/procedures/modifyCaDefaults.ts, src/base/Context.ts, src/base/__tests__/Context.ts, src/testUtils/mocks/dataSources.ts
This method closes the connection with the middleware and chain. The client is then flagged as
disconnected and throws errors if attempting to do anything with it
=> feat(client): add the `disconnect` method

src/api/entities/Instruction/__tests__/index.ts, src/api/entities/Instruction/index.ts
Exists checks are not required, as it is not possible to get a non-existant Instruction instance
=> refactor(instructions): remove unnecessary exists checks on instructions

src/api/entities/Identity/__tests__/index.ts, src/api/entities/Identity/index.ts, src/api/entities/SecurityToken/__tests__/index.ts, src/api/entities/SecurityToken/index.ts, src/api/entities/SecurityToken/types.ts, src/testUtils/mocks/entities.ts
Additionally `isTokenPIARole` checks if the Identity is a PIA or a FullAgent
=> feat(securitytoken): add `fullAgents` property to SecurityToken details

src/utils/__tests__/conversion.ts, src/utils/constants.ts, src/utils/conversion.ts
BREAKING CHANGE: `api.transferPolyx` and `portfolio.moveFunds` now throw an error if the memo string
is longer than 32 characters
=> fix(transfers): validate and pad memo length

src/api/entities/SecurityToken/__tests__/index.ts, src/api/entities/SecurityToken/index.ts, src/api/entities/SecurityToken/types.ts, src/api/procedures/__tests__/consumeAuthorizationRequests.ts, src/api/procedures/__tests__/createSecurityToken.ts, src/api/procedures/__tests__/setPermissionGroup.ts, src/api/procedures/consumeAuthorizationRequests.ts, src/api/procedures/createSecurityToken.ts, src/testUtils/mocks/entities.ts, src/types/index.ts, src/types/internal.ts, src/utils/__tests__/conversion.ts, src/utils/conversion.ts
- when creating a Security Token, if the token type in the inputs is a custom type that hasn’t
been registered, an additional transaction is submitted to register it
- when creating a Security Token, only ask for permission to add documents if the documents
array has elements
- request the correct transaction permissions when accepting an authorization request
=> feat: support new custom asset type system

src/base/Procedure.ts, src/base/__tests__/Procedure.ts, src/types/internal.ts
- procedures can now have different permission requirements for
secondary keys and external agents
=> chore: 🤖 allow specifying different signer and agent perms

src/base/Context.ts, src/base/__tests__/Context.ts
Previously, we were forcing a total disconnect when the polkadot.js API
emitted 'disconnect' or 'error' events. That was not necessary, since
polkadot.js already handles automatic reconnects
=> fix: 🐛 allow polkadot.js to handle disconnects by itself

src/api/entities/SecurityToken/CorporateActions/__tests__/index.ts, src/api/entities/SecurityToken/CorporateActions/index.ts, src/api/entities/SecurityToken/CorporateActions/types.ts, src/api/procedures/__tests__/modifyCaDefaultConfig.ts, src/api/procedures/modifyCaDefaultConfig.ts, src/internal.ts, src/testUtils/mocks/entities.ts
BREAKING CHANGE: 🧨 rename `CorporateActionDefaults` to `CorporateActionDefaultConfig`,
`setDefaults` to `setDefaultConfig`, `getDefaults` to `getDefaultConfig`
within the `CorporateActions` entity.
=> refactor: 💡 MSDK-750 Rename CADefaults to CADefaultConfig

src/utils/__tests__/conversion.ts, src/utils/conversion.ts
`authorizationDataToAuthorizationType` didn't have a code branch for
this type of authorization, causing errors when fetching
=> fix: 🐛 support fetching `BecomeAgent` authorizations

src/base/Context.ts, src/base/__tests__/Context.ts, src/testUtils/mocks/dataSources.ts, src/types/index.ts
BREAKING CHANGE: 🧨 change the `Balance` interface's `free` balance to represent actual free
balance (to pay fees or transfer), and `total` to represent actual total
balance. This affects the `Account.getBalance` method
=> fix: 🐛 use proper calculations for account balances

src/utils/__tests__/conversion.ts, src/utils/conversion.ts
Pads the ticker that is passed to the token.transferOwnership method to
prevent an incorrect length error from being thrown
=> fix: 🐛 Transfer Ownership method

.eslintrc, src/middleware/__tests__/queries.ts
For linting ignore only the types.ts file in middleware instead the
entire directory.
=> chore: 🤖 Tighten middleware lint ignore rule

src/api/procedures/__tests__/createSecurityToken.ts, src/api/procedures/createSecurityToken.ts
BREAKING CHANGE: 🧨 `TickerReservation.createToken` now takes `initialSupply` instead of
`totalSupply` parameter for specifying amount of tokens that will be
minted on creation
=> feat: 🎸 MSDK-756 Change `totalSupply` to `initialSupply` on asset creation

src/api/procedures/__tests__/modifyDistributionCheckpoint.ts, src/api/procedures/modifyDistributionCheckpoint.ts
https://polymath.atlassian.net/browse/MSDK-774
Removed the redundant expiry date check from `modifyDistributionCheckpoint` procedure and updated the validation message for paymentDate validation to _“Cannot modify a Distribution checkpoint after the payment date”_
=> chore: 🤖 Remove redundant expiry date check

src/base/PolymeshTransactionBase.ts, src/testUtils/mocks/dataSources.ts
Using this option will account for pending transactions when auto
incrementing the account nonce. This allows for a better experience when
submitting multiple transactions for a single account. Each transaction
needs time to end up in the transaction pool, so some wait time may
still be needed.
=> feat: 🎸 Use nonce: -1 for signAndSend

README.md
Without this option enabled, a project importing the SDK will fail type checking
[Slack convo](https://polymathnetwork.slack.com/archives/C026L2FKT25/p1643920406272279?thread_ts=1643918647.591449&cid=C026L2FKT25)
=> docs: ✏️ Add note about enabling skipLibCheck in README

src/api/entities/Identity/IdentityAuthorizations.ts, src/api/entities/Identity/__tests__/IdentityAuthorizations.ts, src/api/entities/common/namespaces/__tests__/Authorizations.ts, src/testUtils/mocks/dataSources.ts, src/testUtils/types/index.ts
https://polymath.atlassian.net/browse/DA-252
`IdentityAuthorizations.getOne` - This method overrides the `getOne` method from base class `Authorizations` and will fetch Authorization Request, targeting or issued by the parent Identity, by its ID
=> feat: 🎸 Add `getOne` method in `IdentityAuthorizations`

.github/pull_request_template.md, src/api/entities/Account.ts, src/api/entities/__tests__/Account.ts
Currently the signing Identity was used to get the permissions that an Account had as a Permissioned Account. This change replaces the use of `signingIdentity` with the corresponding identity associated with the Account and then uses that to fetch the permissions. Also, throws an error if the Account is not associated with any Identity
🧨 `account.getPermissions` can throw if there is no Identity associated with the Account
DA-290
❌  Updated the Readme.md (if required) ?
=> fix: 🐛 DA-290 Replace signing identity with account identity while fetching account permissions

package.json, yarn.lock
Added dependency `websocket-as-promised` required to update README.
=> chore: 🤖 Add websocket-as-promised dependency

src/Assets.ts, src/__tests__/Assets.ts, src/api/entities/TickerReservation/__tests__/index.ts, src/api/entities/TickerReservation/index.ts, src/utils/__tests__/conversion.ts, src/utils/__tests__/internal.ts, src/utils/conversion.ts, src/utils/internal.ts
Regardless of the state, `assets.getReservation` now returns a `TickerReservation` instance.
🧨 `assets.isTickerAvailable` has been removed. 
To check ticker availability, directly get the `TickerReservation` instance and use `details.status` to check the availability
DA-142
=> feat: 🎸 Always return `TickerReservation` from `assets.getTickerReservation`

src/api/procedures/__tests__/controllerTransfer.ts, src/api/procedures/controllerTransfer.ts
`controllerTransfer` procedure used to throw the following error when trying to transfer the Asset to a self Portfolio - 
```
asset.SenderSameAsReceiver:  Transfers to self are not allowed
```
This PR add the missing validation -> checks if the originPortfolio DID is same as the signingIdentity DID, it throws `ErrorCode.UnmetPrerequisite` with apt message
DA-304
=> fix: 🐛 Add missing validations in `controllerTransfer` proc

package.json, scripts/fetchDefinitions.js, scripts/generateCountryCodes.js, scripts/generateTxTags.js
This PR moves generation of the `CountryCode` enum and its respective conversion utils to its own script, which uses the fetched metadata instead of the schema. 
It also modifies the script that generates TxTags to use the previously fetched metadata instead of fetching it again
https://polymath.atlassian.net/browse/DA-321
=> Da 323/country code enum

package.json, yarn.lock
polkadot api introduced breaking changes with their BTreeSet around
8.3.1. We need to pin our dependencies so consumers get a working
version
Issue discovered when working on [DA-348](https://polymath.atlassian.net/browse/DA-348)
=> fix: 🐛 Pin polkadot dependencies

src/api/entities/Asset/__tests__/index.ts, src/api/entities/Asset/index.ts
This changes the logic for calculation of investor count for an asset. 
* If PUIS is disabled, `asset.balanceOf` is used to fetch count of identities with non-zero balances. 
* If PUIS is enabled, `asset.scopeIdOf` is used to lookup all ScopeIds for a ticker before the count of identities with non-zero balances is queried using `asset.balanceOfAtScope`.
DA-322
=> feat: 🎸 Proper calculation of investor count with PUIS enabled

src/api/procedures/__tests__/inviteExternalAgent.ts, src/api/procedures/__tests__/utils.ts, src/api/procedures/inviteExternalAgent.ts, src/api/procedures/utils.ts, src/utils/__tests__/conversion.ts
When adding an external agent, we used to throw an error if the passed
permissions corresponded to an existing group. Now that group is fetched
and used to create the authorization
no longer throw an error when adding an external agent with explicit
permissions if there is already an existing permission group with those
permissions
=> feat: 🎸 support passing existing group permissions

src/api/procedures/__tests__/modifyCaDefaultConfig.ts, src/api/procedures/modifyCaDefaultConfig.ts
Make `modifyCaDefaultConfig` use batching for every transaction to prepare for eliminating Transaction Queues
=> feat: 🎸 use batching when modifying CA defaults

src/api/procedures/__tests__/modifyInstructionAffirmation.ts
I've been noticing my PR test runs have been flaky due to a particular test case.
For now I doubled the time for it to hopefully prevent the flakiness.
N/A
[DA-380](https://polymath.atlassian.net/browse/DA-380)
=> test: 💍 separate the two expectations into different tests to reduce ci flakiness on affirmation tests

src/api/procedures/createTransactionBatch.ts, src/base/PolymeshTransactionBatch.ts, src/base/__tests__/PolymeshTransactionBatch.ts, src/utils/__tests__/internal.ts, src/utils/internal.ts, src/utils/typeguards.ts
Add a `splitTransactions` method to the `PolymeshTransactionBatch` class
that returns all individual transactions in the batch. This method is
useful when the caller is being subsidized, since batches do not support
subsidies
This PR adds a `splitTransactions` method to the `PolymeshTransactionBatch` class that returns all individual transactions in the batch. This method is useful when the caller is being subsidized, since batches do not support subsidies
https://polymath.atlassian.net/browse/DA-162?atlOrigin=eyJpIjoiODBiNzUyYjQ2YmM2NDI2YmE2YWE4ZmYxM2Y3YzlmZDIiLCJwIjoiaiJ9
=> feat: 🎸 support splitting batches

README.md
triggers release of latest alpha as the previous merge had older commits
skipped be semver bot
Feat/da 148 eliminate transaction queues (#785)
* feat: remove Transaction Queues
The `TransactionQueue` class has been removed. Most of its methods have been moved over to
`PolymeshTransaction` and `PolymeshTransactionBatch`. Methods that returned a `TransactionQueue`
(all endpoints that write to the blockchain, such as `sdk.assets.registerTicker`) now return
either a `PolymeshTransaction` or `PolymeshTransactionBatch`. This means that all operations
in the SDK are now atomic and not prone to race conditions or half-states
- The `onProcessedByMiddleware` method has been moved to `PolymeshTransaction` and
`PolymeshTransactionBase`
- The `Fees` interface now contains a `total` property which is …
=> feat: 🎸 release elimination of transaction queues

src/base/Procedure.ts
in Procedure `prepare` method, the passed in, non modified `context` was
used, when `ctx` was supposed to be used instead
[DA-405](https://github.com/PolymeshAssociation/polymesh-sdk/pull/831#issuecomment-1227689597)
=> fix: 🐛 fix bug where only the default signer was used

src/base/PolymeshTransactionBatch.ts, src/types/index.ts
The original types weren't being properly reflected by the compiler, resulting in an array of only 2 transactions always. Also, when batching transactions that had a transformed return value, the compiler was throwing errors. Since we don't care about the original return value, only the transformed one, using `any` is acceptable (`unknown` resulted in errors as well)
=> fix: 🐛 improve the typing of `splitTransactions`

src/api/client/AccountManagement.ts, src/api/entities/Asset/TransferRestrictions/TransferRestrictionBase.ts, src/api/entities/Asset/TransferRestrictions/__tests__/TransferRestrictionBase.ts, src/api/entities/MultiSig/index.ts, src/api/procedures/__tests__/addAssetStat.ts, src/api/procedures/__tests__/addTransferRestriction.ts, src/api/procedures/__tests__/createAsset.ts, src/api/procedures/__tests__/removeAssetStat.ts, src/api/procedures/__tests__/setTransferRestrictions.ts, src/api/procedures/addAssetStat.ts, src/api/procedures/removeAssetStat.ts, src/api/procedures/types.ts, src/testUtils/mocks/dataSources.ts, src/types/index.ts, src/types/internal.ts, src/utils/__tests__/conversion.ts, src/utils/__tests__/internal.ts, src/utils/conversion.ts, src/utils/internal.ts
cleans up doc gen warnings around multiSig references and StatType not being exposed in the docs
I moved the MultiSig files late in the PR process, but forgot about the @link refs to it. This PR cleans up the warnings.
It also exposes `StatType` for transfer restrictions, as this is used to discriminate the input types. Although the user doesn't need this (we set it in the namespace), TSDocs warned about it not being shown. 
N/A
N/A (I noticed this when doing DA-407)
=> docs: ✏️ fix doc warnings for multiSig + StatType

src/base/PolymeshTransactionBase.ts, src/base/__tests__/PolymeshTransactionBase.ts
Adds a getter `result` to PolymeshTransactionBase class. this will have the result resolved from run() so it can be accessed later
✅ Closes: [DA-407](https://polymesh.atlassian.net/browse/DA-407)
=> feat: 🎸 add result to successfully ran transactions

src/api/procedures/setTransferRestrictions.ts, src/base/Context.ts, src/base/__tests__/Context.ts, src/testUtils/mocks/dataSources.ts, src/types/utils/index.ts, src/utils/__tests__/internal.ts, src/utils/internal.ts
Methods such as `<query>.at(..args)` and `<query>.entriesAt(...args)` were deprecated from Polkadot in favour of first getting a decorated api at any block with `api.at(<blockHash>)` and then using the `query` module within it to get the desired result. This change updates all occurrence to use the latest logic
NA
[DA-410](https://polymesh.atlassian.net/browse/DA-410)
=> chore: 🤖 use api.at(<blockhash>) for querying old blocks

src/api/procedures/__tests__/createTransactionBatch.ts, src/base/PolymeshTransaction.ts, src/base/PolymeshTransactionBase.ts, src/base/PolymeshTransactionBatch.ts, src/base/Procedure.ts, src/base/__tests__/PolymeshTransaction.ts, src/base/__tests__/PolymeshTransactionBase.ts, src/base/__tests__/PolymeshTransactionBatch.ts, src/types/index.ts, src/types/internal.ts
Introduces a new ProdecureOpt to allow a user to specify transaction mortality. A user can now specify imortal transactions, or for a specific number of blocks the transaction should be valid for
None
[DA-416](https://polymesh.atlassian.net/browse/DA-416)
=> feat: 🎸 allow specifying transaction mortality

src/api/entities/types.ts
Exports `MetadataEntry` from `api/entities/types`, so that SDK consumers can import it from `types` instead of `internal`
NA
[DA-426](https://polymesh.atlassian.net/browse/DA-426)
=> feat: 🎸 Export `MetadataEntry` from `types`

src/base/PolymeshTransactionBase.ts, src/base/__tests__/PolymeshTransactionBase.ts, src/types/index.ts
allow user to specify how many blocks a transaction should be valid for. Note the maximum effective value is 250 as of chain v5.1.0, as this is the value of `BlockHashCount`, which is the number of block hashes accesible to the runtime. If the block hash is not found the transaction is assumed expired
✅ Closes: [DA-416](https://polymesh.atlassian.net/browse/DA-416)
=> feat: 🎸 allow `lifetime` param for mortal procedure opts

src/api/client/Polymesh.ts, src/polkadot/augment-api-rpc.ts, src/polkadot/augment-types.ts, src/polkadot/definitions.ts, src/polkadot/group/definitions.ts, src/polkadot/group/index.ts, src/polkadot/group/types.ts, src/polkadot/polymesh/definitions.ts, src/polkadot/polymesh/types.ts, src/polkadot/schema.ts, src/polkadot/types.ts
On running the SDK, following warning were logged in console - 
```
2022-10-07 16:38:14        REGISTRY: Unknown signed extensions StoreCallMetadata found, treating them as no-effect
2022-10-07 16:38:14        API/INIT: RPC methods not decorated: group_getCDDValidMembers, group_getGCValidMembers
2022-10-07 16:38:15        REGISTRY: Unknown signed extensions StoreCallMetadata found, treating them as no-effect
```
Apparently, group pallet was missing and polkadot wasn't able to find the custom signed extension.
Updated rpcs to with missing group pallet and passed custom signed extensions while initialising polkadot
NA
DA-431
=> chore: 🤖 Get rid of polkadot js warning

scripts/postProcessTypes.js, src/api/entities/CustomPermissionGroup.ts, src/api/entities/__tests__/CustomPermissionGroup.ts, src/polkadot/augment-api-query.ts
This prevents `CustomPermissionGroup.exists()` from breaking for id equal to max sequence value and also removes post processing of query states. 
Error - 
```
TypeError: context.polymeshApi.query.externalAgents.aGIdSequence is not a function
```
NA
DA-443
=> fix: 🐛 Update the logic around `agIdSequence`

src/api/client/AccountManagement.ts, src/api/procedures/inviteAccount.ts, src/api/procedures/modifySignerPermissions.ts, src/api/procedures/subsidizeAccount.ts, src/api/procedures/transferPolyx.ts, src/api/procedures/types.ts, src/utils/__tests__/internal.ts, src/utils/internal.ts
Changes the account type in `ModifySignerPermissionsParams` from `Account` to `string | Account`. This allows us to pass address of the account directly while modifying/revoking permissions for a secondary account.
This change is required for REST API
NA
DA-47
=> feat: 🎸 Support account type string for secondary accounts

package.json, patches/@polkadot+types+8.9.1.patch, tsconfig.json, yarn.lock
The types package for polkadot (`@polkadot/types`) only declares the lookup module and expects it to be implemented by the consumer. SDK uses the `yarn polkadot-types-from-defs` to generate the types correctly. The allows the compiler to understand that at runtime packages will be available but intellisense doesn't work with lookup types. This change helps fix that and compiler gets to know about the types at compile time.
NA
DA-427
=> chore: 🤖 Modify `lookup.d.ts` in @polkadot/types to fix typings

package.json
as a dev dependency users need patch-package installed globally when installing
None
None
=> fix: 🐛 move patch-package to dependency from devDependency

src/api/procedures/__tests__/registerMetadata.ts, src/api/procedures/registerMetadata.ts, src/utils/internal.ts
Following error was currently thrown 
```
2022-11-29 16:38:36             VEC: Unable to decode on index 1 Expected an array of 2 values as params to a Map query
2022-11-29 16:38:36        RPC-CORE: subscribeStorage(keys?: Vec<StorageKey>): StorageChangeSet:: createType(Vec<StorageKey>):: Expected an array of 2 values as params to a Map query
2022-11-29 16:38:36             DRR: createType(Vec<StorageKey>):: Expected an array of 2 values as params to a Map query
~/polymesh-rest-api-cloned/node_modules/@polkadot/types-create/cjs/create/type.js:73
firstError = new Error(`createType(${type}):: ${error.message}`);
^
Error: createType(Vec<StorageKey>):: Expected an array of 2 values as params to a Map query
```
`queryMulti` expects an array of arguments with query storage allows more than one …
=> fix: 🐛 Handle queryMulti params correctly

src/api/entities/Account.ts, src/api/entities/Subsidies.ts, src/api/entities/__tests__/Subsidies.ts
Adds `Subsidies` namespace which contains two methods -
* `getBeneficiaries` - to get list of all subsidy relationship along with allowance where the Account is the subsidizer
* `getSubsidizer` - get the Subsidy relationship along with allowance where the Account is the beneficiary
NA
DA-196
=> feat: 🎸 Add Subsidies namespace

src/base/Context.ts, src/base/__tests__/Context.ts, src/testUtils/mocks/dataSources.ts
when setting an external signing manager for the SDK, also set it on sdk._polkadotApi property for convenience.
Working on the batch mock cdd endpoint the external signer wasn't being used, and thats because we never set it directly on the underling instance.
In the REST API we are able to call the `setSigner` method ourselves, but its cleaner for the SDK to call the method.
- None
=> fix: 🐛 set external signer on polkadot api instance

src/utils/__tests__/internal.ts, src/utils/constants.ts
The node version is v5.1.3 now. I think it will take a while to get operators to upgrade, but alpha shouldn't error with latest from chain imo.
[Change](https://github.com/PolymeshAssociation/Polymesh/commit/27ab6d5548cd4d220fb3119f312c2d8868466743#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L3)
=> feat: 🎸 support chain node v5.1.3

src/types/index.ts, src/types/utils/index.ts
Adds `\` for proper rendering of <T> in docs + exports missing v2 types needed in documentation
NA
NA
=> docs: ✏️ Add backtick around <T> and export missing v2 types

src/api/procedures/__tests__/addInstruction.ts, src/api/procedures/addInstruction.ts
Prevent adding instruction leg with same from & to DID
🧨 `addInstruction` procedure now throws an error if any leg contains same from & to DIDs
DA-479
=> fix: 🐛 Prevent adding instruction leg with same from & to DID

src/types/index.ts
the chain has increased the BlockHashCount, which allows users to specify a longer `lifetime` for their transactions
Chain PR is [here](https://github.com/PolymeshAssociation/Polymesh/pull/1375)
n/a
n/a
=> docs: ✏️ update comment to reflect longer `lifetime` in tx opts

src/api/procedures/__tests__/quitCustody.ts, src/api/procedures/quitCustody.ts
fix bug where the procedure context differs from the portfolio context
The issue happens when using the non default signer to leave the default signer's portfolio since the `context` variable is different between the objects.
n/a
n/a
=> fix: 🐛 allow non default signer to quit portfolios

.github/workflows/main.yml, package.json
when moving package.json into `dist` relative paths need to be updated
I was trying to bring the SDK in with [Skypack](https://www.skypack.dev/) and the message that prints is:
```
[Package Error] "@polymeshassociation/polymesh-sdk@v18.1.0" could not be built. 
[1/5] Verifying package is valid…
[2/5] Installing dependencies from npm…
[3/5] Building package using esinstall…
Running esinstall...
We resolved "@polymeshassociation/polymesh-sdk" to @polymeshassociation/polymesh-sdk/dist/index.js, but the file does not exist on disk.
We resolved "@polymeshassociation/polymesh-sdk" to /tmp/cdn/_74a1lUfzbqwqneABTBpY/node_modules/@polymeshassociation**/polymesh-sdk/dist/index.js,** but the file does not exist on disk.
```
=> fix: 🐛 update path for package.json "main" and "types" files

src/api/client/AccountManagement.ts, src/api/client/__tests__/AccountManagement.ts
add sync method to validate address strings. `getAccount` implicitly validates the address, however is async making it less versatile
When I added multisig, I made `getAccount` async, which adds extra checks. This lets people check just the address is OK
=> feat: 🎸 add validate account method

src/api/entities/Asset/types.ts, src/api/procedures/__tests__/createAsset.ts, src/api/procedures/createAsset.ts, src/api/procedures/types.ts
Remove option to add investor uniqueness for an asset
🧨 `requiresInvestorUniqueness` is now removed from `CreateAssetParams`
=> feat: 🎸 Remove option to add investor uniqueness for an asset

src/api/entities/AuthorizationRequest.ts, src/api/entities/__tests__/AuthorizationRequest.ts, src/api/procedures/__tests__/consumeAddRelayerPayingKeyAuthorization.ts, src/api/procedures/__tests__/consumeAuthorizationRequests.ts, src/api/procedures/consumeAddRelayerPayingKeyAuthorization.ts, src/api/procedures/consumeAuthorizationRequests.ts, src/internal.ts
As of now, when the beneficiary with zero amount tried accepting the subsidy auth for adding paying key, SDK threw an error, preventing the target to accept the subsidy. This PR adds a separate procedure to handle `AddRelayerPayingKey` type of authorization, where now the issuer pays for the acceptance/rejection of authorization by the target beneficiary.
NA
NA
=> fix: 🐛 Add new procedure to handle `AddRelayerPayingKey` auth

src/api/procedures/__tests__/modifyInstructionAffirmation.ts, src/api/procedures/modifyInstructionAffirmation.ts
As of now, if a user tried to affirm/withdraw/reject instruction with non-existing portfolio, SDK threw an error stating that `Portfolio doesn't exists`. With this change, modify instruction procedure now handles the non-existing portfolios as well. This was use-case generally needed to reject instructions created with non-existing portfolios. More description in the JIRA ticket.
NA
DA-753
=> fix: 🐛 Allow modify instruction with non-existing portfolios

.github/workflows/main.yml, src/api/entities/Instruction/__tests__/index.ts, src/api/entities/Instruction/index.ts
This adds `getInvolvedPortfolios` to Instruction entity which returns all the portfolios in an Instruction, where a given DID is custodian of
NA
DA-757
=> feat: 🎸 Add method to get involved portfolios in an instruction 

src/api/client/Settlements.ts, src/api/entities/Instruction/__tests__/index.ts, src/api/entities/Instruction/index.ts, src/api/procedures/__tests__/executeManualInstruction.ts, src/api/procedures/executeManualInstruction.ts, src/api/procedures/types.ts
instruction `executeManually` method now accepts optional `skipAffirmationCheck` param. Useful when processing the affirmation earlier in the batch transaction.
None
[DA-756](https://polymesh.atlassian.net/browse/DA-756)
[DA-756]: https://polymesh.atlassian.net/browse/DA-756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 allow for skiping affirm for manual execution

src/api/procedures/__tests__/modifyInstructionAffirmation.ts, src/api/procedures/modifyInstructionAffirmation.ts
6.0 removes the need to specify leg count for affirmations. Previously would fail with expecting 2 got 3 args error
None
N/A
=> fix: 🐛 instruction affirmation does not need leg count

.eslintrc, package.json, src/api/client/Polymesh.ts, src/api/client/__tests__/Polymesh.ts, src/base/Context.ts, src/base/__tests__/Context.ts, src/middleware/queries.ts, src/middleware/queriesV2.ts, src/testUtils/mocks/dataSources.ts, yarn.lock
The apollo default import implictly depends on react. by only importing from `@apollo/client/core` instead of `@apollo/client` react is not needed.
https://github.com/apollographql/apollo-client/issues/7005#issuecomment-691248887
None
N/A
=> feat: 🎸 remove react dependency

src/api/entities/Asset/index.ts
5.4 should not unwrap the already `Bytes` name
None
N/A
=> fix: 🐛 `asset.details` on v5.4

src/api/client/Polymesh.ts, src/api/client/__tests__/Polymesh.ts, src/base/Context.ts, src/base/__tests__/Context.ts, src/testUtils/mocks/dataSources.ts, src/types/index.ts, src/utils/__tests__/internal.ts, src/utils/internal.ts
add polkadot options so people can provide metadata to improve startup time. optimizes the rest of `Polymesh.connect` to further improve startup time
- parallizes version checks on connect
- lazy evaluates `isArchiveNode` when needed
- add `polkadot` option to connect. consumer can provide metadata
✅ Closes: DA-838
=> perf: ⚡️ improve startup time

src/base/Context.ts, src/testUtils/mocks/dataSources.ts
bug was introduced with dual version support because RPC methods are not automatically generated. 5.4 was expecting newer return type. fix works by aliasing the new type name to old response on 5.4
None
N/A
=> fix: 🐛 `canTransfer` method for 5.4 with dual version

package.json, yarn.lock
The `9.1.2` version of `bignumber.js` doesn't export `./bignumber` path in it's package.json file which errors as `Error
[ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './bignumber' is not defined by "exports"`
NA
NA
=> fix: 🐛 Use `9.0.1` version for `bignumber.js`

README.md
NodeJS version 16 (LTS) is the minimum supported version for executing Polymesh SDK.
=> fix: readme file (minimum node version support)

src/api/procedures/__tests__/createAsset.ts, src/api/procedures/__tests__/issueTokens.ts, src/api/procedures/createAsset.ts, src/api/procedures/issueTokens.ts, src/api/procedures/types.ts, src/testUtils/mocks/entities.ts
Adds posibility to set portfolio to which the Asset will be issued when creating asset (if the initial supply gt 0) and when issuing tokens;
https://polymesh.atlassian.net/browse/DA-833
=> feat: 🎸 select portfolio on asset issuance

src/api/client/Claims.ts, src/api/client/__tests__/Claims.ts
Changes the implementation of `getCddClaims` to  replaces the use of query storage of `identity.claims` with RPC `identity.validCDDClaims`
NA
DA-888
=> feat: 🎸 Change implementation of `getCddClaims` to use RPC

src/api/client/Assets.ts
fixes `getAssets` method which would fail for certain tickers
None
N/A
=> fix: 🐛 getAssets where ticker was not being padded for query

src/api/entities/Identity/__tests__/index.ts, src/api/entities/Identity/index.ts
Add method to check if an identity is a child identity. This add `isChild` method to the `Identity` entity
NA
DA-892
=> feat: 🎸 Add method to check if an identity is a child identity

src/api/entities/Account/__tests__/index.ts, src/api/entities/Account/index.ts
`getMultiSig()` was returning address of the account from which the method was invoked. This correctly now returns the multisig it is part of
NA
DA-897
=> fix: 🐛 Return MultiSig address from `account.getMultiSig` func

src/api/entities/Asset/NonFungible/Nft.ts, src/api/entities/Asset/__tests__/NonFungible/Nft.ts, src/api/entities/Asset/__tests__/NonFungible/NftCollection.ts, src/api/entities/Portfolio/__tests__/index.ts, src/api/entities/Portfolio/index.ts, src/api/entities/Portfolio/types.ts, src/api/procedures/__tests__/issueNft.ts, src/api/procedures/__tests__/moveFunds.ts, src/api/procedures/__tests__/redeemTokens.ts, src/api/procedures/moveFunds.ts, src/testUtils/mocks/entities.ts, src/types/index.ts, src/utils/__tests__/conversion.ts, src/utils/__tests__/internal.ts, src/utils/conversion.ts, src/utils/internal.ts, src/utils/typeguards.ts
Add `.getCollections` to portfolios to retrieve held NFTs. `portfolio.moveFunds` has been extended to support NFT movements.
None
[DA-879](https://polymesh.atlassian.net/browse/DA-879)
[DA-879]: https://polymesh.atlassian.net/browse/DA-879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 add NFT support for portfolios

src/api/entities/Account/MultiSig/index.ts, src/api/entities/Account/__tests__/MultiSig.ts
`multisig.proposalIds` doesn't correctly store the proposals for a multisig. This PR fixes the implementation of `getProposals` in multisig entity to fetch the proposals using `multisig.proposals` chain storage
NA
DA-898
=> fix: 🐛 Use `multisig.proposals` to fetch proposals

src/api/entities/Asset/NonFungible/NftCollection.ts, src/api/entities/Asset/__tests__/NonFungible/NftCollection.ts, src/api/entities/Asset/types.ts, src/api/procedures/__tests__/issueNft.ts, src/api/procedures/issueNft.ts, src/testUtils/mocks/entities.ts
Return more information for collection metadata so its easier to see what each key should be
`collection.collectionMetadataKeys()` is renamed to `collection.collectionMetadata()` (method was `alpha` branch only)
Originally implemented: [DA-876](https://polymesh.atlassian.net/browse/DA-876)
[DA-876]: https://polymesh.atlassian.net/browse/DA-876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 expand collection metadata spec and name

src/api/entities/MultiSigProposal/__tests__/index.ts, src/api/entities/MultiSigProposal/index.ts, src/api/entities/MultiSigProposal/types.ts, src/types/index.ts
previously multisig proposals.details() would return args as string[], they are now `AnyJson` to include the type name as a key
BREAKING CHANGE: 🧨 MultiSigProposal.details() now returns JSON instead of string[]
✅ Closes: [DA-906](https://polymesh.atlassian.net/browse/DA-906)
[DA-906]: https://polymesh.atlassian.net/browse/DA-906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 add type names to proposal args

src/api/client/Assets.ts, src/api/client/__tests__/Assets.ts, src/api/entities/Asset/NonFungible/NftCollection.ts, src/api/entities/Asset/__tests__/NonFungible/NftCollection.ts, src/api/entities/Asset/types.ts, src/api/procedures/__tests__/issueNft.ts, src/api/procedures/createNftCollection.ts, src/api/procedures/issueNft.ts, src/testUtils/mocks/entities.ts
Add type `Asset` as union of FungibleAsset and NftCollection. `getAsset` method added for use cases where the type doesn't matter, e.g. adding documents. 
`NftCollection.collectionMetadata` renamed to `collectionKeys` for consistency with storage (alpha only method)
[DA-878](https://polymesh.atlassian.net/browse/DA-878)
[DA-878]: https://polymesh.atlassian.net/browse/DA-878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 Add `getAsset` method to Assets namespace

src/api/entities/Asset/NonFungible/Nft.ts, src/api/entities/Asset/__tests__/NonFungible/Nft.ts
Minor optimization to query key ID directly using `assetMetadataGlobalNameToKey` instead of `assetMetadataGlobalKeyToName.entries` and filtering by name.
=> Use `assetMetadataGlobalNameToKey` instead of `assetMetadataGlobalKeyToName.entries` and filtering by name

src/api/procedures/__tests__/addInstruction.ts, src/api/procedures/__tests__/moveFunds.ts, src/api/procedures/addInstruction.ts, src/api/procedures/moveFunds.ts
check to ensure 'amount' and 'nfts' are present in fungible and NFT movements respectively
This can happen when using the ticker instead of asset entities, otherwise TS will ensure the right field is there
None
N/A
=> feat: 🎸 add check to ensure NFT movement has correct args

src/api/entities/Account/__tests__/index.ts, src/api/entities/Account/index.ts
With changes in SQ, the current logic was not returning the list of transactions. Removing the extra encoding part fixes the problem
NA
DA-949
=> fix: 🐛 Correct the logic for `account.getTransactionHistory`

src/utils/constants.ts
Prevents warning when connecting to 6.1 chains
None
None
=> fix: 🐛 warning when connecting to 6.1 chains

src/api/entities/Asset/Fungible/index.ts, src/api/entities/Asset/__tests__/Fungible/index.ts, src/api/entities/Asset/types.ts, src/middleware/queries.ts, src/utils/__tests__/internal.ts, src/utils/constants.ts
PR updates the middleware types to fetch in the new attributes from SQ and adds optional `instructionId`, `instructionMemo` and `fundingRound` attributes to `HistoricAssetTransaction`.
=> feat: 🎸 Add new attributes to HistoricAssetTransaction

src/api/entities/Asset/NonFungible/Nft.ts, src/api/entities/Asset/__tests__/NonFungible/Nft.ts
This adds in condition to correctly return false when checking existence for NFT id 0
NA
DA-998
=> fix: 🐛 Correct the logic of `nft.exists`

src/api/client/Network.ts, src/types/index.ts
previously it was `Record<string, unknown>`, which is annoying to use as a consumer
None, actual data returned is the same
Noticed during [DA-974](https://polymesh.atlassian.net/browse/DA-974)
[DA-974]: https://polymesh.atlassian.net/browse/DA-974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 add type annotations for `submitTransaction` return

src/api/client/ConfidentialSettlements.ts, src/api/client/Polymesh.ts, src/api/client/__tests__/ConfidentialSettlements.ts, src/api/entities/confidential/ConfidentialTransaction/index.ts, src/api/entities/confidential/ConfidentialVenue/index.ts, src/api/entities/confidential/__tests__/ConfidentialTransaction/index.ts, src/api/entities/confidential/__tests__/ConfidentialVenue/index.ts, src/api/entities/types.ts, src/internal.ts, src/testUtils/mocks/entities.ts
* Adds `ConfidentialVenue` and `ConfidentialTransaction` entity with basic `exists` and `toHuman` method
* `ConfidentialVenue` also has `creator` method to fetch the creator of the venue
* Adds `ConfidentialSettlements` namespace that will handle all venue and transaction related functions. For now `getVenue` and `getTransaction` has been added
NA
DA-988, DA-989, DA-990
=> feat: 🎸 Add entities to manage confidential venue & transaction

src/api/entities/confidential/ConfidentialAccount/index.ts, src/api/entities/confidential/ConfidentialAsset/index.ts, src/api/entities/confidential/ConfidentialAsset/types.ts, src/api/entities/confidential/__tests__/ConfidentialAccount/index.ts, src/api/entities/confidential/__tests__/ConfidentialAsset/index.ts, src/api/entities/types.ts, src/internal.ts, src/testUtils/mocks/dataSources.ts, src/testUtils/mocks/entities.ts
* Adds in `ConfidentialAccount` entity. This also has `getIdentity` method to get DID mapped with the CA
* Adds in `getAuditors` to `ConfidentialAsset` to get auditors (mapped by type) for a CA
NA
DA-987
DA-1014
=> feat: 🎸 Add `ConfidentialAccount` entity and method to get confidential Asset auditors

src/api/entities/confidential/ConfidentialTransaction/index.ts, src/api/entities/confidential/__tests__/ConfidentialTransaction/index.ts
allows for subscription to confidential transaction status changes
none
✅ Closes: [DA-995](https://polymesh.atlassian.net/browse/DA-995)
[DA-995]: https://polymesh.atlassian.net/browse/DA-995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 add `onStatusChange` to confidential transaction

src/api/entities/Identity/__tests__/index.ts, src/api/entities/Identity/index.ts, src/api/entities/confidential/ConfidentialTransaction/index.ts, src/api/entities/confidential/__tests__/ConfidentialTransaction/index.ts, src/testUtils/mocks/dataSources.ts, src/types/index.ts, src/utils/__tests__/conversion.ts, src/utils/conversion.ts
add method for users to get confidential transactions involving their affirmation
add method to get number of pending affirmations on a confidential transaction
None
✅ Closes: [DA-993](https://polymesh.atlassian.net/browse/DA-993)
[DA-993]: https://polymesh.atlassian.net/browse/DA-993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 add `getInvolvedConfidentialTransactions` to Identity

.github/workflows/main.yml, src/api/entities/CheckpointSchedule/index.ts, src/api/entities/Identity/index.ts, src/api/entities/confidential/ConfidentialTransaction/index.ts, src/api/entities/confidential/ConfidentialTransaction/types.ts, src/api/entities/confidential/__tests__/ConfidentialTransaction/index.ts, src/api/procedures/__tests__/affirmConfidentialTransactions.ts, src/api/procedures/__tests__/rejectConfidentialTransaction.ts, src/api/procedures/affirmConfidentialTransactions.ts, src/api/procedures/rejectConfidentialTransaction.ts, src/internal.ts, src/testUtils/mocks/dataSources.ts, src/testUtils/mocks/entities.ts, src/utils/__tests__/conversion.ts, src/utils/conversion.ts
also adds `getLegState` and `getLegStates` on confidential transaction to help retrieve proof info
None
[DA-982](https://polymesh.atlassian.net/browse/DA-982)
[DA-982]: https://polymesh.atlassian.net/browse/DA-982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 add affirm/reject methods for confidential transaction

src/api/procedures/__tests__/addInstruction.ts, src/api/procedures/addInstruction.ts, src/api/procedures/types.ts
allows for optional field `mediators` when creating instructions. These are additional entities required to affirm the instruction before it can be executed
None (will fallback to old extrinsics on unupgraded chains)
✅ Closes: [DA-1021](https://polymesh.atlassian.net/browse/DA-1021)
[DA-1024]: https://polymesh.atlassian.net/browse/DA-1024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DA-1021]: https://polymesh.atlassian.net/browse/DA-1021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 allows for optional field `mediators` for instructions

src/api/entities/Instruction/__tests__/index.ts, src/api/entities/Instruction/index.ts, src/api/procedures/__tests__/modifyInstructionAffirmation.ts, src/api/procedures/modifyInstructionAffirmation.ts, src/api/procedures/types.ts
adds a set of methods to allow instruction mediators to manage their affirmation status
None
✅ Closes: [DA-1022](https://polymesh.atlassian.net/browse/DA-1022)
[DA-1022]: https://polymesh.atlassian.net/browse/DA-1022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 add {affirm,reject,withdraw}_as_mediator to Instruction

src/api/procedures/__tests__/addInstruction.ts, src/api/procedures/addAssetMediators.ts, src/api/procedures/addInstruction.ts, src/api/procedures/modifyInstructionAffirmation.ts, src/utils/__tests__/internal.ts, src/utils/internal.ts
fixes a bug where mediators would not be allowed to affirm due to non mediator validation. also adds validation to ensure mediators exist
None
Bug introduced from: [DA-1022](https://polymesh.atlassian.net/browse/DA-1022)
[DA-1022]: https://polymesh.atlassian.net/browse/DA-1022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: 🐛 allow mediators to affirm when not involved in trade

src/api/entities/Instruction/__tests__/index.ts, src/api/procedures/__tests__/executeManualInstruction.ts, src/api/procedures/executeManualInstruction.ts, src/api/procedures/types.ts
users had to specify instruction id to execute manually, now it is inferred from the instruction entity
ID can no longer be passed into execute manually (it wasn't supposed to be allowed)
N/A
=> fix: 🐛 execute manual instruction type

src/api/procedures/executeManualInstruction.ts
update handling of instruction weights to allow affirm instruction to be batched with execute manually. The RPC underestimates the weight if the instruction has not yet been affirmed
None
N/A
=> fix: 🐛 allow exec manual to be batched with affirm instruction

src/base/Procedure.ts
use `defusePromise` to prevent process crashes from unhandled promise rejections. Previously node would exit before user code had a chance to handle it.
None
✅ Closes:[ #1116](https://github.com/PolymeshAssociation/polymesh-sdk/issues/1116)
=> fix: 🐛 crash due to unhandled promise rejection

src/api/entities/Asset/Base/Settlements/index.ts, src/api/entities/Asset/__tests__/Base/Settlements.ts, src/api/entities/Identity/__tests__/index.ts, src/api/entities/Identity/index.ts, src/api/procedures/__tests__/toggleTickerPreApproval.ts, src/api/procedures/toggleTickerPreApproval.ts, src/internal.ts, src/testUtils/mocks/dataSources.ts, src/testUtils/mocks/entities.ts
Adds `asset.settlements.preApprove` and
`asset.settlements.removePreApproval` methods to allow identities to automatically affirm receiving certain assets. Adds getter methods `identity.preApprovedAssets` and `identity.isAssetPreApproved` to allow checking pre-approvals.
✅ Closes: [DA-1080](https://polymesh.atlassian.net/browse/DA-1080)
[DA-1080]: https://polymesh.atlassian.net/browse/DA-1080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 adds ability to pre-approve receiving assets

src/api/procedures/__tests__/addInstruction.ts, src/api/procedures/addInstruction.ts
This will allow to set an older block as `endAfterBlock` while creating an instruction, eventually allowing the manual execution at any time
NA
DA-1129
=> fix: 🐛 Remove future block constraint on `endAfterBlock`

src/api/client/Network.ts, src/api/client/Polymesh.ts, src/api/client/__tests__/Network.ts, src/testUtils/mocks/dataSources.ts, src/utils/__tests__/internal.ts, src/utils/constants.ts, src/utils/internal.ts
allows for SDK to connect and interact with polymesh private networks. Some internal properties are now marked "protected" instead of "private" to allow extension. Middleware types updated to latest SQ
None
=> feat: 🎸 allow connection to polymesh private networks

src/api/entities/Asset/NonFungible/AssetHolders/index.ts, src/api/entities/Asset/NonFungible/NftCollection.ts, src/api/entities/Asset/__tests__/NonFungible/AssetHolders.ts, src/api/entities/Asset/types.ts, src/middleware/__tests__/queries.ts, src/middleware/queries.ts
add `assetHolders.get` to NFT collections for fetching all holders of an NFT collection, along with the specific NFTs they hold
✅ Closes: [DA-1004](https://polymesh.atlassian.net/browse/DA-1004)
[DA-1004]: https://polymesh.atlassian.net/browse/DA-1004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 Add asset holders namespace for NFT collections

README.md, package.json, scripts/consts.js, scripts/updateReadme.js, src/types/index.ts, yarn.lock
* Bumps dependencies to remove security alerts
* Modifies logic of `updateReadme` script to correctly update README using version from constant file
* Clean up uniqueness comment
NA
DA-1147, DA-1146, DA-872
=> fix: 🐛 Bump dependencies to remove security alerts

src/base/Context.ts
removes redundant private variable. The variable was made redundant in commit `2450467` (chain v5 upgrade).
None (removed variable `_polymeshApi` was declared private, on a private class)
=> refactor: 💡 remove redundant private `_polymeshApi` in Context

scripts/prepareCodeForDocs.js, sdk-docs-typedoc.json, src/utils/typeguards.ts, typedoc.json
After last change, type docs was giving bunch of warning for missing types from `entities/types.ts` because it was exluded from typedoc generation. This will include `entities/types.ts` in typedoc generation
NA
DA-1151
=> fix: 🐛 include `entities/types.ts` in typedoc generation

src/api/procedures/__tests__/toggleTickerPreApproval.ts, src/api/procedures/toggleTickerPreApproval.ts
correct authorization logic that was preventing non asset agents from pre-approving assets
None
None
=> fix: 🐛 allow non-agents to pre-approve assets

src/api/entities/Asset/Fungible/Issuance/index.ts, src/api/entities/Asset/Fungible/index.ts, src/api/entities/Asset/NonFungible/NftCollection.ts, src/api/entities/Asset/__tests__/NonFungible/NftCollection.ts, src/api/procedures/__tests__/issueNft.ts, src/api/procedures/__tests__/issueTokens.ts, src/api/procedures/issueNft.ts, src/api/procedures/issueTokens.ts, src/api/procedures/types.ts, src/internal.ts
When the option was added to specify portfolio on issuance, the interface didn't get updated (https://github.com/PolymeshAssociation/polymesh-sdk/pull/1025/files). This adds the option to specify portfolio on issuance. 
(This was encountered while covering edge cases in middleware tests.)
NA
NA
=> feat: 🎸 Add option to issue tokens in a specific portfolio

src/api/entities/DividendDistribution/__tests__/index.ts, src/api/entities/DividendDistribution/index.ts, src/middleware/__tests__/queries.ts, src/middleware/queries.ts
After the latest changes in SQ wrt historical state tracking, the graphql queries querying the node entity directly expect `_id: UUID!` instead of the `id: ID!`, causing a couple of queries to break. 
This PR changes the format of both the queries to work correctly. 
NA
NA
=> fix: 🐛 Update middleware queries to support latest graphql

src/api/entities/Asset/Base/Metadata/index.ts, src/api/entities/Asset/__tests__/Base/Metadata.ts, src/utils/constants.ts
Replaces the deprecated usage of `assetMetadataNextLocalKey` with `currentAssetMetadataLocalKey`. This is supported with 6.3 changes
NA
DA-1200
=> feat: 🎸 Use `currentAssetMetadataLocalKey` to get next local ID

src/api/entities/Account/MultiSig/index.ts, src/api/entities/Account/__tests__/MultiSig.ts, src/api/procedures/__tests__/joinCreator.ts, src/api/procedures/joinCreator.ts, src/api/procedures/types.ts, src/internal.ts
allows multiSig to directly join creator identity without the need for accepting an authorization
None
✅ Closes: [DA-1250](https://polymesh.atlassian.net/browse/DA-1250)
[DA-1250]: https://polymesh.atlassian.net/browse/DA-1250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 add `MultiSig.joinCreator` method

README.md, src/api/client/Polymesh.ts, src/api/client/__tests__/Polymesh.ts, src/utils/__tests__/internal.ts, src/utils/internal.ts
`Polymesh.connect` throws catchable connect errors. Previously it would crash on node, or clutter the console with `Abnormal closure` in the browser
✅ Closes: [DA-1251](https://polymesh.atlassian.net/browse/DA-1251)
[DA-1251]: https://polymesh.atlassian.net/browse/DA-1251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: 🐛 throw catchable connect errors

src/api/client/__tests__/AccountManagement.ts, src/api/entities/Account/__tests__/index.ts, src/utils/internal.ts
previously a MultiSig with no signers would be mistaken for a regular account. This occurs when no account has accepted the authorization
None
None
=> fix: 🐛 return MultiSig from getAccount with no signers

src/api/client/Network.ts, src/api/client/__tests__/Network.ts, src/api/client/types.ts
add `result: ISubmittable` to `SubmittableResult`, allowing consumers to read event data for their submitted transaction
[DA-1221](https://polymesh.atlassian.net/browse/DA-1221)
[DA-1221]: https://polymesh.atlassian.net/browse/DA-1221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 add `result` when submitting offline transactions

src/api/entities/Account/MultiSig/index.ts, src/api/entities/Account/__tests__/MultiSig.ts, src/api/procedures/__tests__/evaluateMultiSigProposal.ts, src/api/procedures/__tests__/linkTickerToAsset.ts, src/api/procedures/__tests__/modifyMultiSig.ts, src/api/procedures/evaluateMultiSigProposal.ts, src/api/procedures/modifyMultiSig.ts, src/base/PolymeshTransactionBase.ts, src/base/__tests__/PolymeshTransactionBase.ts, src/testUtils/mocks/entities.ts
fix issues when creating proposals due to some calls not being updated to the getAdmin/getPayer calls vs legacy getCreator call
=> fix: 🐛 v7 multiSig errors by using payer/admin over creator

.github/workflows/main.yml, package.json, src/api/entities/Account/MultiSig/index.ts, src/api/procedures/__tests__/evaluateMultiSigProposal.ts, src/api/procedures/__tests__/modifyMultiSig.ts, src/api/procedures/evaluateMultiSigProposal.ts, src/api/procedures/modifyMultiSig.ts, src/api/procedures/types.ts, yarn.lock
- allows a multiSig propoposal to be rejected by creator if no other votes have been casted
- allows modifying the required signatures for a multiSig
https://polymesh.atlassian.net/browse/DA-1288
=> fix: 🐛 allow reject a proposal by creator with no other votes + modify required signatures

src/api/procedures/__tests__/consumeJoinOrRotateAuthorization.ts, src/api/procedures/__tests__/utils.ts, src/api/procedures/types.ts, src/api/procedures/utils.ts
previously the auth `rotatePrimaryKeyToSecondary` was unable to be accepted by a key already joined to the identity, although it is allowed by the chain
None
✅ Closes: DA-1310
=> fix: 🐛 allow joined account to accept rotate to secondary auth

src/testUtils/mocks/dataSources.ts, src/utils/__tests__/conversion.ts, src/utils/conversion.ts
fixes an issue where compliance requirements using custom types would cause `asset.compliance.requirements.get()` to fail
✅ Closes: DA-1319
=> fix: 🐛 allow asset requirements with custom types to be read

src/types/index.ts
allow users to reference values of InstructionStatusEnum by exporting it as a value instead of only the type
None
=> refactor: 💡 export InstructionStatusEnum as value, not as type

package.json, src/api/entities/Asset/Base/Settlements/index.ts, src/api/entities/Asset/__tests__/Base/Settlements.ts, src/polkadot/polymesh/definitions.ts, src/polkadot/polymesh/types.ts, src/polkadot/schema.ts, yarn.lock
- updated polymesh-types package to `5.12.3`
- regenerated types - added missing `count` paramater to `Authorization` type to fix decoding of `identityApi.getFilteredAuthorizations` responses
- removed conversion of portfolio custodian did to `PolymeshPrimitiveIdentityId` for `assetApi.canTransferGranular` calls as it required type for per the schema was `Option<IdentityId>` and did not accept `PolymeshPrimitiveIdentityId` as an acceptable type. The explicit conversion to a Codec type is not required.
N/A
N/A
=> Fix runtime API calls

package.json, src/api/entities/Asset/Base/Settlements/index.ts, src/api/entities/Asset/__tests__/Base/Settlements.ts, src/polkadot/polymesh/definitions.ts, src/polkadot/polymesh/types.ts, src/polkadot/schema.ts, yarn.lock
- updated polymesh-types package to 5.12.3
- regenerated types - added missing count paramater to Authorization type to fix decoding of identityApi.getFilteredAuthorizations responses
- removed conversion of portfolio custodian did to PolymeshPrimitiveIdentityId for assetApi.canTransferGranular calls as it required type for per the schema was Option<IdentityId> and did not accept PolymeshPrimitiveIdentityId as an acceptable type. The explicit conversion to a Codec type is not required.
N/A
=> Alpha into Beta

package.json, src/api/entities/Asset/Base/Settlements/index.ts, src/api/entities/Asset/__tests__/Base/Settlements.ts, src/polkadot/polymesh/definitions.ts, src/polkadot/polymesh/types.ts, src/polkadot/schema.ts, yarn.lock
- updated polymesh-types package to `5.12.3`
- regenerated types - added missing `count` paramater to `Authorization` type to fix decoding of `identityApi.getFilteredAuthorizations` responses
- removed conversion of portfolio custodian did to `PolymeshPrimitiveIdentityId` for `assetApi.canTransferGranular` calls as it required type for per the schema was `Option<IdentityId>` and did not accept `PolymeshPrimitiveIdentityId` as an acceptable type. The explicit conversion to a Codec type is not required.
=> Beta into Master

src/api/entities/Account/MultiSig/index.ts, src/api/entities/Asset/Base/Settlements/index.ts, src/api/entities/Asset/__tests__/Base/Settlements.ts, src/api/entities/Asset/types.ts, src/testUtils/mocks/dataSources.ts, src/utils/__tests__/conversion.ts, src/utils/conversion.ts
Uses statistics runtime API to get transfer restriction errors in transferring an asset.
NA
DA-1315
=> chore: 🤖 use stats runtime API to get transfer restriction errs

src/api/entities/Asset/types.ts, src/api/entities/Instruction/types.ts
Updates interfaces with notes about ticker deprecation
- Since its not mandatory to specify a ticker while creating an Asset,
`ticker` field in `BaseAsset` is now optional. `did` field in `BaseAsset` is now also optional.
- Since an instruction can be created without specifying a venue, `venue` field in `InstructionDetails` is now nullable.
- `TickerReservationDetails` optionally returns `assetId` when the status is `TickerReservationStatus.AssetCreated`.
- `ticker` field in `CreateNftCollectionParams` is now optional. Also, a new optional field `assetId` has been added to specify ID of the asset while creating NFT collection.
- `Ticker` value has been marked as deprecated in favour of new `Asset` value for the enums: `ScopeType` and `ClaimScopeTypeEnum`
- `ticker` field has been …
=> docs: ✏️ Update interfaces with notes about ticker deprecation

src/api/entities/Asset/Base/BaseAsset.ts, src/api/entities/Asset/__tests__/Fungible/index.ts, src/api/entities/Asset/types.ts
Return ticker from BaseAsset.details method
`ticker`, `did` has been deprecated in `BaseAsset`. To get the ticker associated with an Asset, use `BaseAsset.details` method which now returns `ticker` along with other Asset details
DA-1326
=> feat: 🎸 return `ticker` from `BaseAsset.details` method

src/api/entities/Asset/types.ts, src/utils/__tests__/conversion.ts, src/utils/conversion.ts
Some of the errors handling was missing in `canTransfer` method. This adds those checks
NA
DA-1352
=> fix: 🐛 Handle self transfer case when checking asset transfer

src/api/client/Settlements.ts, src/api/client/__tests__/Settlements.ts, src/api/client/types.ts, src/api/entities/Identity/__tests__/index.ts, src/api/entities/Identity/index.ts, src/middleware/__tests__/queries/settlements.ts, src/middleware/queries/settlements.ts
- enables pagination on Identity.getHistoricalInstuctions
- adds filter by  assetId, ticker, status, sender,  receiver,  mediator,  party to Identity.getHistoricalInstuction
- adds getHistoricalInstuctions to Settlements class
https://polymesh.atlassian.net/browse/DA-1340
=> feat: 🎸 add  pagination, filters to getHistoricalInstructions

src/utils/__tests__/conversion.ts, src/utils/conversion.ts
scopeToMiddlewareScope was not correctly modifying the incoming scope in order to filter out data from SQ entities. Old attribute `value` was still used instead of new `assetId` in case of ScopeType.Asset. This correctly now maps the same.
NA
DA-1359
=> fix: 🐛 Correctly handle scopeToMiddlewareScope for Asset types

.github/workflows/docs.yml, .github/workflows/main.yml, package.json, yarn.lock
There was a problem with semantic-release where releasing an alpha just after releasing a beta version would fail (As it would try to re-create the last alpha tag). This was because channel notes on the latest head were getting updated to `beta`, and when semantic-release used to find out last alpha already released it used to skip the last and get the second last and try to release the last alpha version again. 
Semantic-release already adapted to the logic to shift adding notes to tags instead of git heads. 
Latest semantic-release fixes our issue automatically
NA
DA-1354
=> chore: 🤖 Bump semantic-release version to `24.2.0`

src/utils/__tests__/conversion.ts, src/utils/conversion.ts
When an instruction had two or more legs with sender portfolio as same, the creation of BtreeSet of portfolioIds was failing because of duplicate items in the list. This fixes the issue by only using unique items in the list.
NA
=> fix: 🐛 Use unique portfolios while creating BtreeSet

src/api/entities/Instruction/__tests__/index.ts, src/api/entities/Instruction/index.ts, src/api/entities/Instruction/types.ts, src/api/entities/types.ts, src/middleware/queries/settlements.ts, src/utils/conversion.ts
Add option to query information from middleware for instruction related methods.
🧨 Methods in the `Instruction` entity that retrieve information from the
chain were updated to use middleware for fetching data, when available. If middleware is
unavailable, the methods will continue to fetch data directly from the chain.
The following methods were modified with this logic: `details`, `getAffirmations`, `getLegs`,
`getMediators`, `getOffChainAffirmations`, `getOffChainAffirmationForLeg`.
When querying via middleware, these methods will now throw an error in the following cases:
a. If the instruction does not exist.
b.If the instruction data has not yet been processed by the middleware.
Also, the pagination options for `getAffirmations` and `getLegs` now supports
`MiddlewarePaginationOptions` …
=> feat: 🎸 Retrieve instruction info from middleware(if available) 

src/api/client/__tests__/Polymesh.ts, src/testUtils/mocks/dataSources.ts, src/utils/__tests__/internal.ts, src/utils/constants.ts, src/utils/internal.ts
SDK now uses runtime API so the RPC version check is redundant
None
[DA-1372](https://polymesh.atlassian.net/browse/DA-1372)
[DA-1372]: https://polymesh.atlassian.net/browse/DA-1372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 skip RPC version check

src/api/entities/Instruction/__tests__/index.ts, src/api/entities/Instruction/index.ts, src/api/procedures/__tests__/executeManualInstruction.ts, src/api/procedures/__tests__/modifyInstructionAffirmation.ts, src/api/procedures/executeManualInstruction.ts, src/api/procedures/modifyInstructionAffirmation.ts, src/base/Context.ts, src/base/__tests__/Context.ts, src/testUtils/mocks/dataSources.ts
`Instruction.getLegs` was modified to use middleware to fetch the leg information. This caused the affirm/execution procedure to wait for the instruction to be synced via middleware before affirming/executing (when middleware was available).
NA
=> fix: 🐛 Fetch legs from chain while instruction affirm/execution

src/api/entities/Instruction/__tests__/index.ts, src/api/entities/Instruction/index.ts, src/api/procedures/__tests__/executeManualInstruction.ts, src/api/procedures/__tests__/modifyInstructionAffirmation.ts, src/api/procedures/executeManualInstruction.ts, src/api/procedures/modifyInstructionAffirmation.ts, src/base/Context.ts, src/base/__tests__/Context.ts, src/testUtils/mocks/dataSources.ts, src/testUtils/mocks/entities.ts
When an instruction is queried we check that the instruction ID is less than or equal to the instruction counter from the chain. Description in metadata states `InstructionCounter - Number of instructions in the system (It's one more than the actual number)`. As a result if we query an instruction one more than the latest instruction the chain SDK doesn't throw an error when it should. This fixes the same logic
NA
DA-1400
=> fix: 🐛 Fix logic to check if instruction exists

src/api/entities/Account/MultiSig/index.ts, src/api/entities/Account/MultiSig/types.ts, src/api/entities/Account/__tests__/MultiSig.ts, src/middleware/queries/multisigs.ts, src/middleware/typesV1.ts, src/utils/__tests__/conversion.ts, src/utils/conversion.ts
`MultiSig.getHistoricalProposals` used to return just the entity object of MultiSigProposal expecting users to fetch details on their own. But while fetching the details, pruned proposal data could not be fetch and SDK throws error on the same. 
This PR introduces new interface `HistoricalMultiSigProposal` which will fetch all the info from middleware and return the same. 
BREAKING CHANGE: 🧨 Return type of `MultiSig.getHistoricalProposals` is now changed to `ResultSet<HistoricalMultiSigProposal>` to provide more info about the proposal. This will allow get know information about prunded proposals as well
DA-1391
=> feat: 🎸 Add more info about historical proposal

src/api/entities/Portfolio/__tests__/index.ts, src/api/entities/Portfolio/index.ts, src/api/procedures/__tests__/configureDividendDistribution.ts, src/api/procedures/configureDividendDistribution.ts, src/utils/__tests__/internal.ts, src/utils/internal.ts
When currency was passed as a ticker value, asset balances were not correctly fetched, causing the procedure to fail erroneously. This fixes the logic for getting asset balances as well as handles currency being passed as  a ticker value as well.
NA
DA-1406
=> fix: 🐛 Correctly handle currency as ticker when configuring DD

src/api/entities/Instruction/__tests__/index.ts, src/api/entities/Instruction/index.ts
With new event `FailedToExecuteInstruction` being tracked by SQ for failed events, SDK was not returning the status as failed for failed instructions. 
DA-1408
=> fix: 🐛 Correctly return status for failed instructions

src/api/entities/Identity/__tests__/AssetPermissions.ts, src/api/entities/__tests__/CustomPermissionGroup.ts, src/utils/__tests__/conversion.ts, src/utils/conversion.ts, src/utils/strings.ts
if a user inputs permissions directly on chain there is no validation of their cases. This updates it so incorrect cased permissions are ignored
✅ Closes: [DA-1397](https://polymesh.atlassian.net/browse/DA-1397)
[DA-1397]: https://polymesh.atlassian.net/browse/DA-1397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: 🐛 ignore improper cased permissions

src/api/entities/Instruction/index.ts
Convert `tradeDate` and `valueDate` middleware date/times to `Date`
=> Fix type for `tradeDate` and `valueDate` in instruction details when queried from middleware

src/api/entities/Instruction/__tests__/index.ts, src/api/entities/Instruction/index.ts
Handle null `Instruction.tradeDate` and `valueDate`
=> Handle null `Instruction.tradeDate`

src/api/entities/Account/__tests__/index.ts, src/api/entities/Account/index.ts, src/api/entities/Identity/__tests__/index.ts, src/api/entities/Identity/index.ts, src/middleware/__tests__/queries/assets.ts, src/middleware/__tests__/queries/extrinsics.ts, src/middleware/queries/assets.ts, src/middleware/queries/extrinsics.ts, src/middleware/queries/settlements.ts
Fix offChainAffirmations, instructionAffirmations order by. Handle CREATED_AT order by in getTransactionHistory, getHeldAssets and getHeldNfts by replacing it with CREATED_BLOCK_ID order instead (which is equivalent in SQv19+). Created at ordering is marked as deprecated and will be removed when SQ v18 is no longer supported
DA-1434
=> fix: 🐛 handle createdAt order by for SQ v19+

src/api/procedures/registerIdentity.ts
register identity would error when receiving an Account object (address string was fine). This updates it to use the generic input handler
=> fix: 🐛 error when passing Account to register identity

src/api/entities/Account/Staking/index.ts, src/api/entities/Account/__tests__/Staking.ts, src/api/procedures/__tests__/nominateValidators.ts, src/api/procedures/nominateValidators.ts, src/api/procedures/types.ts, src/internal.ts
add `account.staking.nominate` method to allow a controller to select validators
[DA-208](https://polymesh.atlassian.net/browse/DA-208)
[DA-208]: https://polymesh.atlassian.net/browse/DA-208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 allow controller to nominate validators

src/api/client/Settlements.ts, src/api/client/__tests__/Settlements.ts, src/api/client/types.ts, src/api/entities/Identity/__tests__/index.ts, src/api/entities/Identity/index.ts, src/middleware/__tests__/queries/settlements.ts, src/middleware/queries/settlements.ts
- fixes issue where querying historical instructions would result in duplicate entries being returned
- none
https://polymesh.atlassian.net/browse/DA-1446
=> fix: 🐛 duplicate entries returned on historicalInstructions

src/api/client/Staking.ts, src/api/client/__tests__/Staking.ts, src/api/entities/Account/Staking/index.ts, src/api/entities/Account/__tests__/Staking.ts
remove staking methods from the `Account` namespace and attach them to the SDK staking namespace. `account.staking.bond` -> `sdk.staking.bond`. The signing account was always the acting account and the parent account was not relevant
N/A
=> Move unreleased staking tx methods

src/utils/__tests__/internal.ts, src/utils/internal.ts
no longer warn when the chain is on a new minor version
=> style: 💄 skip warn for chain minor upgrade

src/api/procedures/__tests__/nominateValidators.ts, src/api/procedures/nominateValidators.ts
make sure at least one nominator is set and ensure none are blocked
=> feat: 🎸 add extra validation for nominate procedure

src/api/procedures/__tests__/setStakingPayee.ts, src/api/procedures/setStakingPayee.ts
consider autoStake when calculating NoDataChange error
=> fix: 🐛 allow payee to set auto stake for themselves

src/base/Procedure.ts, src/base/__tests__/Procedure.ts
adds a method on Procedure to be able to get required authorizations before executing the procedure
https://polymesh.atlassian.net/browse/DA-1409
=> feat: 🎸 get permissions required for a procedure

src/api/entities/CustomPermissionGroup.ts, src/api/entities/Identity/AssetPermissions.ts, src/api/entities/types.ts, src/generated/types.ts, src/utils/__tests__/conversion.ts, src/utils/__tests__/internal.ts, src/utils/constants.ts, src/utils/conversion.ts, src/utils/internal.ts
adds `unmatchedPermissions` for PermissionedAccount to return a list of permissions that the PermissionedAccount has but that are not present in SDK (wrong module name, incorrect extrinsic, or a combination)
https://polymesh.atlassian.net/browse/DA-1412
=> feat: 🎸 add field to expose unmatched permissions

src/api/client/Network.ts, src/api/client/__tests__/Network.ts, src/base/types.ts, src/testUtils/mocks/dataSources.ts, src/utils/typeguards.ts
allow users to pass in only the inner payload in `network.submitTransaction`
None
[DA-1451](https://polymesh.atlassian.net/browse/DA-1451)
[DA-1451]: https://polymesh.atlassian.net/browse/DA-1451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 allow submitting offline tx with just `payload`

src/api/client/Assets.ts, src/api/client/__tests__/Assets.ts, src/api/procedures/types.ts, src/base/Procedure.ts, src/base/__tests__/Procedure.ts
* Adds in optional `skipExistsCheck` to methods of Assets class to get fungible and non-fungible asset
* Adds optional `skipChecks` to `ProcedureOpts` to allow skipping of various checks at procedure level
DA-1465
=> feat: 🎸 Add optional skip checks for procedures and on getting asset

src/api/procedures/__tests__/addTransferRestriction.ts, src/api/procedures/addTransferRestriction.ts, src/api/procedures/types.ts
Adds an optional argument to skip checking if stat is enabled when adding a TransferRestriction to make it possible to batch these kind of transactions
NA
DA-1496
=> feat: 🎸 add option to avoid checking if stat is enabled

src/api/entities/Asset/Fungible/TransferRestrictions/TransferRestrictionBase.ts, src/api/entities/Asset/Fungible/TransferRestrictions/__tests__/TransferRestrictionBase.ts, src/api/entities/DefaultTrustedClaimIssuer.ts, src/api/entities/types.ts, src/testUtils/mocks/dataSources.ts, src/utils/__tests__/conversion.ts, src/utils/conversion.ts
- allows specifying customClaimTypeId when adding/modifying TrustedClaimIssuer for an Asset
- return of `asset.compliance.trustedClaimIssuers.get()` will be an object in case of CustomClaim of shape { type: ClaimType.Custom, customClaimTypeId: BigNumber } 
https://polymesh.atlassian.net/browse/DA-1463
=> fix: 🐛 allow specify customClaimTypeId for TrustedClaimIssuer
